Geant4 VMC: TG4RadiatorDescription Class Reference
TG4RadiatorDescription Class Reference
geometry
The radiator description.
#include <TG4RadiatorDescription.h>
Public Types
using Component = std::tuple<G4String, G4double, G4double>
Public Member Functions
TG4RadiatorDescription (const G4String &volumeName="")
~TG4RadiatorDescription ()
void PrintParameters () const
void SetVolumeName (const G4String &name)
Set the name of associated volume.
void SetXtrModel (const G4String &name)
Set the transition radiation process model.
void SetFoilNumber (G4int foilNumber)
Set the number of foils.
void SetLayer (const G4String &materialName, G4double thickness, G4double fluctuation)
void SetStrawTube (const G4String &materialName, G4double wallThickness, G4double gasThickness)
G4String GetVolumeName () const
Return the name of associated volume.
G4String GetXtrModel () const
Return the transition radiation process model.
G4int GetFoilNumber () const
Return the number of foils.
Component GetLayer (G4int i) const
Component GetStrawTube () const
Return the straw tube parameters.
Private Attributes
G4String fVolumeName
The name of associated volume.
G4String fXtrModel
The transition radiation process model.
G4int fFoilNumber
The number of foils.
std::vector< Component > fLayers
The layer parameters.
Component fStrawTube
The straw tube parameters.
Detailed Description
The radiator description.
The class defines the radiator parameters which are used by transition radiation processes.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 31 of file TG4RadiatorDescription.h.
Member Typedef Documentation
Component
using TG4RadiatorDescription::Component = std::tuple<G4String, G4double, G4double>
Definition at line 34 of file TG4RadiatorDescription.h.
Constructor & Destructor Documentation
TG4RadiatorDescription()
TG4RadiatorDescription::TG4RadiatorDescription (const G4String & volumeName = "")
Default constructor
Definition at line 19 of file TG4RadiatorDescription.cxx.
~TG4RadiatorDescription()
TG4RadiatorDescription::~TG4RadiatorDescription ()
Destructor
Definition at line 30 of file TG4RadiatorDescription.cxx.
Member Function Documentation
PrintParameters()
void TG4RadiatorDescription::PrintParameters () const
SetVolumeName()
void TG4RadiatorDescription::SetVolumeName (const G4String & name) inline
Set the name of associated volume.
Definition at line 79 of file TG4RadiatorDescription.h.
SetXtrModel()
void TG4RadiatorDescription::SetXtrModel (const G4String & name) inline
Set the transition radiation process model.
Definition at line 85 of file TG4RadiatorDescription.h.
Referenced by TG4DetConstructionMessenger::SetNewValue().
SetFoilNumber()
void TG4RadiatorDescription::SetFoilNumber (G4int foilNumber) inline
Set the number of foils.
Definition at line 91 of file TG4RadiatorDescription.h.
Referenced by TG4DetConstructionMessenger::SetNewValue().
SetLayer()
void TG4RadiatorDescription::SetLayer (const G4String & materialName, G4double thickness, G4double fluctuation)
Definition at line 36 of file TG4RadiatorDescription.cxx.
Referenced by TG4DetConstructionMessenger::SetNewValue().
SetStrawTube()
void TG4RadiatorDescription::SetStrawTube (const G4String & materialName, G4double wallThickness, G4double gasThickness)
Definition at line 43 of file TG4RadiatorDescription.cxx.
Referenced by TG4DetConstructionMessenger::SetNewValue().
GetVolumeName()
G4String TG4RadiatorDescription::GetVolumeName () const inline
Return the name of associated volume.
Definition at line 97 of file TG4RadiatorDescription.h.
Referenced by TG4TransitionRadiationPhysics::CreateXTRProcess().
GetXtrModel()
G4String TG4RadiatorDescription::GetXtrModel () const inline
Return the transition radiation process model.
Definition at line 103 of file TG4RadiatorDescription.h.
Referenced by TG4TransitionRadiationPhysics::CreateXTRProcess().
GetFoilNumber()
G4int TG4RadiatorDescription::GetFoilNumber () const inline
Return the number of foils.
Definition at line 109 of file TG4RadiatorDescription.h.
Referenced by TG4TransitionRadiationPhysics::CreateXTRProcess().
GetLayer()
TG4RadiatorDescription::Component TG4RadiatorDescription::GetLayer (G4int i) const
Definition at line 50 of file TG4RadiatorDescription.cxx.
Referenced by TG4TransitionRadiationPhysics::CreateXTRProcess().
GetStrawTube()
TG4RadiatorDescription::Component TG4RadiatorDescription::GetStrawTube () const inline
Return the straw tube parameters.
Definition at line 116 of file TG4RadiatorDescription.h.
Referenced by TG4TransitionRadiationPhysics::CreateXTRProcess().
Member Data Documentation
fVolumeName
G4String TG4RadiatorDescription::fVolumeName private
The name of associated volume.
Definition at line 61 of file TG4RadiatorDescription.h.
Referenced by GetVolumeName(), SetVolumeName(), and TG4RadiatorDescription().
fXtrModel
G4String TG4RadiatorDescription::fXtrModel private
The transition radiation process model.
Definition at line 64 of file TG4RadiatorDescription.h.
Referenced by GetXtrModel(), SetXtrModel(), and TG4RadiatorDescription().
fFoilNumber
G4int TG4RadiatorDescription::fFoilNumber private
The number of foils.
Definition at line 67 of file TG4RadiatorDescription.h.
Referenced by GetFoilNumber(), SetFoilNumber(), and TG4RadiatorDescription().
fLayers
std::vector<Component> TG4RadiatorDescription::fLayers private
The layer parameters.
Definition at line 70 of file TG4RadiatorDescription.h.
Referenced by GetLayer(), SetLayer(), and TG4RadiatorDescription().
fStrawTube
Component TG4RadiatorDescription::fStrawTube private
The straw tube parameters.
Definition at line 73 of file TG4RadiatorDescription.h.
Referenced by GetStrawTube(), SetStrawTube(), and TG4RadiatorDescription().
The documentation for this class was generated from the following files:
source/geometry/include/TG4RadiatorDescription.h
source/geometry/src/TG4RadiatorDescription.cxx