Geant4 VMC: TG4StepManager Class Reference
TG4StepManager Class Reference
digits_hits
Geant4 implementation of the TVirtualMC interface methods for access to Geant4 at step level.
#include <TG4StepManager.h>
Public Member Functions
TG4StepManager (const TString &userGeometry)
~TG4StepManager ()
void LateInitialize ()
void StopTrack ()
void InterruptTrack ()
void StopEvent ()
void StopRun ()
void SetStep (G4Step *step, TG4StepStatus status)
void SetStep (G4Track *track, TG4StepStatus status)
void SetStep (G4GFlashSpot *gflashSpot, TG4StepStatus status)
void SetSteppingManager (G4SteppingManager *manager)
void SetMaxStep (Double_t step)
void SetMaxStepBack ()
void SetMaxNStep (Int_t maxNofSteps)
void SetCollectTracks (Bool_t collectTracks)
void ForceDecayTime (Float_t pdg)
void SetInitialVMCTrackStatus (TMCParticleStatus *status)
G4Track * GetTrack () const
G4Step * GetStep () const
TG4StepStatus GetStepStatus () const
TG4Limits * GetLimitsModifiedOnFly () const
Bool_t IsCollectTracks () const
G4VPhysicalVolume * GetCurrentPhysicalVolume () const
TG4Limits * GetCurrentLimits () const
Int_t CurrentVolID (Int_t &copyNo) const
Int_t CurrentVolOffID (Int_t off, Int_t &copyNo) const
const char * CurrentVolName () const
const char * CurrentVolOffName (Int_t off) const
const char * CurrentVolPath ()
Bool_t CurrentBoundaryNormal (Double_t &x, Double_t &y, Double_t &z) const
Int_t CurrentMaterial (Float_t &a, Float_t &z, Float_t &dens, Float_t &radl, Float_t &absl) const
Int_t CurrentMedium () const
void Gmtod (Double_t *xm, Double_t *xd, Int_t iflag)
void Gmtod (Float_t *xm, Float_t *xd, Int_t iflag)
void Gdtom (Double_t *xd, Double_t *xm, Int_t iflag)
void Gdtom (Float_t *xd, Float_t *xm, Int_t iflag)
Double_t MaxStep () const
Int_t GetMaxNStep () const
void TrackPosition (TLorentzVector &position) const
void TrackPosition (Double_t &x, Double_t &y, Double_t &z) const
void TrackPosition (Float_t &x, Float_t &y, Float_t &z) const
void TrackMomentum (TLorentzVector &momentum) const
void TrackMomentum (Double_t &px, Double_t &py, Double_t &pz, Double_t &etot) const
void TrackMomentum (Float_t &px, Float_t &py, Float_t &pz, Float_t &etot) const
Double_t TrackStep () const
Double_t TrackLength () const
Double_t TrackTime () const
Double_t Edep () const
Double_t NIELEdep () const
Int_t StepNumber () const
Double_t TrackWeight () const
void TrackPolarization (Double_t &polX, Double_t &polY, Double_t &polZ) const
void TrackPolarization (TVector3 &pol) const
Int_t TrackPid () const
Double_t TrackCharge () const
Double_t TrackMass () const
Double_t Etot () const
Bool_t IsTrackInside () const
Bool_t IsTrackEntering () const
Bool_t IsTrackExiting () const
Bool_t IsTrackOut () const
Bool_t IsTrackDisappeared () const
Bool_t IsTrackStop () const
Bool_t IsTrackAlive () const
Bool_t IsNewTrack () const
Int_t NSecondaries () const
void GetSecondary (Int_t index, Int_t &particleId, TLorentzVector &position, TLorentzVector &momentum)
TMCProcess ProdProcess (Int_t isec) const
Int_t StepProcesses (TArrayI &proc) const
Static Public Member Functions
static TG4StepManager * Instance ()
Private Member Functions
TG4StepManager (const TG4StepManager &right)
Not implemented.
TG4StepManager & operator= (const TG4StepManager &right)
Not implemented.
void CheckTrack () const
void CheckStep (const G4String &method) const
void CheckGflashSpot (const G4String &method) const
void CheckSteppingManager () const
void SetTLorentzVector (G4ThreeVector xyz, G4double t, TLorentzVector &lv) const
const G4VTouchable * GetCurrentTouchable () const
G4VPhysicalVolume * GetCurrentOffPhysicalVolume (G4int off, G4bool warn=false) const
Private Attributes
G4Track * fTrack
current track
G4Step * fStep
current step
G4GFlashSpot * fGflashSpot
current Gflash spot
TG4StepStatus fStepStatus
step status
TG4Limits * fLimitsModifiedOnFly
limits which step limit was modified during tracking
G4SteppingManager * fSteppingManager
G4SteppingManager.
G4String fNameBuffer
buffer for current volume name or path
G4int fCopyNoOffset
volume copy number offset
G4int fDivisionCopyNoOffset
division copy number offset
TG4TrackManager * fTrackManager
Cached pointer to thread-local track manager.
TMCParticleStatus * fInitialVMCTrackStatus
The initial status of a VMC track when it was popped from the VMC stack.
Static Private Attributes
static G4ThreadLocal TG4StepManager * fgInstance = 0
this instance
Detailed Description
Geant4 implementation of the TVirtualMC interface methods for access to Geant4 at step level.
The public methods that do not implement TVirtualMC methods are commented as G4 specific
Author
I. Hrivnacova; IPN, Orsay
Definition at line 55 of file TG4StepManager.h.
Constructor & Destructor Documentation
TG4StepManager() [1/2]
TG4StepManager::TG4StepManager (const TString & userGeometry)
Standard constructor
Parameters
userGeometry User selection of geometry definition and navigation
Set offset for passing copyNo to 1; as G3toG4 decrement copyNo passed by user by 1
Set offset for passing copyNo to 1; to be equivalent to Root geometrical model (Root starts numbering from 1, while Geant4 from 0)
Definition at line 48 of file TG4StepManager.cxx.
Referenced by Instance(), operator=(), and TG4StepManager().
~TG4StepManager()
TG4StepManager::~TG4StepManager ()
Destructor
Definition at line 85 of file TG4StepManager.cxx.
TG4StepManager() [2/2]
TG4StepManager::TG4StepManager (const TG4StepManager & right) private
Not implemented.
Member Function Documentation
Instance()
TG4StepManager * TG4StepManager::Instance () inline static
Return this instance.
Definition at line 212 of file TG4StepManager.h.
Referenced by TG4RunManager::LateInitialize(), TG4SteppingAction::LateInitialize(), and TG4TrackingAction::LateInitialize().
LateInitialize()
void TG4StepManager::LateInitialize ()
Definition at line 201 of file TG4StepManager.cxx.
Referenced by TG4RunManager::LateInitialize().
StopTrack()
void TG4StepManager::StopTrack ()
Stop the current track and skips to the next.
Possible "stop" track status from G4:
fStopButAlive // Invoke active rest physics processes and // and kill the current track afterward
fStopAndKill // Kill the current track (used)
fKillTrackAndSecondaries // Kill the current track and also associated // secondaries.
Definition at line 207 of file TG4StepManager.cxx.
InterruptTrack()
void TG4StepManager::InterruptTrack ()
Interrupt the current track and skip to the next.
Definition at line 229 of file TG4StepManager.cxx.
StopEvent()
void TG4StepManager::StopEvent ()
Abort the current event processing.
Definition at line 244 of file TG4StepManager.cxx.
Referenced by StopRun().
StopRun()
void TG4StepManager::StopRun ()
Abort the current run processing.
Definition at line 257 of file TG4StepManager.cxx.
SetStep() [1/3]
void TG4StepManager::SetStep (G4Step * step, TG4StepStatus status) inline
Set current step and step status.
Definition at line 218 of file TG4StepManager.h.
SetStep() [2/3]
void TG4StepManager::SetStep (G4Track * track, TG4StepStatus status) inline
Set current track and step status.
Definition at line 227 of file TG4StepManager.h.
SetStep() [3/3]
void TG4StepManager::SetStep (G4GFlashSpot * gflashSpot, TG4StepStatus status) inline
Set current track and step status.
Definition at line 236 of file TG4StepManager.h.
SetSteppingManager()
void TG4StepManager::SetSteppingManager (G4SteppingManager * manager) inline
Set G4 stepping manger.
Set navigator !!!
Definition at line 247 of file TG4StepManager.h.
SetMaxStep()
void TG4StepManager::SetMaxStep (Double_t step)
Set the maximum step allowed in the current logical volume; the value is restored after exiting from the current tracking medium
Definition at line 268 of file TG4StepManager.cxx.
SetMaxStepBack()
void TG4StepManager::SetMaxStepBack ()
Restore back the maximum step after exiting from the tracking medium where it has been changed of fly
Definition at line 288 of file TG4StepManager.cxx.
SetMaxNStep()
void TG4StepManager::SetMaxNStep (Int_t maxNofSteps)
Set the maximum number of steps.
Definition at line 305 of file TG4StepManager.cxx.
SetCollectTracks()
void TG4StepManager::SetCollectTracks (Bool_t collectTracks)
(In)Activate collecting TGeo tracks
Definition at line 313 of file TG4StepManager.cxx.
ForceDecayTime()
void TG4StepManager::ForceDecayTime (Float_t pdg)
Force decay time.
Not yet implemented.
Definition at line 321 of file TG4StepManager.cxx.
SetInitialVMCTrackStatus()
void TG4StepManager::SetInitialVMCTrackStatus (TMCParticleStatus * status)
A transported track obtained from the VMC stack might already have a history and therefore e.g. a step number != 0
Definition at line 343 of file TG4StepManager.cxx.
GetTrack()
G4Track * TG4StepManager::GetTrack () const inline
Return current track manger.
Definition at line 261 of file TG4StepManager.h.
GetStep()
G4Step * TG4StepManager::GetStep () const inline
Return current step.
Definition at line 267 of file TG4StepManager.h.
GetStepStatus()
TG4StepStatus TG4StepManager::GetStepStatus () const inline
Return current step status.
Definition at line 273 of file TG4StepManager.h.
GetLimitsModifiedOnFly()
TG4Limits * TG4StepManager::GetLimitsModifiedOnFly () const inline
Return limits that has been modified on fly
Definition at line 279 of file TG4StepManager.h.
IsCollectTracks()
Bool_t TG4StepManager::IsCollectTracks () const
Return the info if collecting tracks is activated
Definition at line 352 of file TG4StepManager.cxx.
GetCurrentPhysicalVolume()
G4VPhysicalVolume * TG4StepManager::GetCurrentPhysicalVolume () const
Return the current physical volume. According to fStepStatus the volume from track vertex, pre step point or post step point is returned.
Definition at line 360 of file TG4StepManager.cxx.
Referenced by CurrentMaterial(), CurrentMedium(), CurrentVolID(), CurrentVolName(), CurrentVolPath(), GetCurrentLimits(), and MaxStep().
GetCurrentLimits()
TG4Limits * TG4StepManager::GetCurrentLimits () const
Return the current limits.
Definition at line 379 of file TG4StepManager.cxx.
Referenced by SetMaxStep().
CurrentVolID()
Int_t TG4StepManager::CurrentVolID (Int_t & copyNo) const
Return the current sensitive detector ID and fill the copy number of the current physical volume
Definition at line 401 of file TG4StepManager.cxx.
Referenced by CurrentVolOffID().
CurrentVolOffID()
Int_t TG4StepManager::CurrentVolOffID (Int_t off, Int_t & copyNo) const
Return the the sensitive detector ID of the off-th mother of the current volume and fill the copy number of its physical volume
Definition at line 422 of file TG4StepManager.cxx.
CurrentVolName()
const char * TG4StepManager::CurrentVolName () const
Return the current physical volume name.
Definition at line 450 of file TG4StepManager.cxx.
Referenced by CurrentVolOffName().
CurrentVolOffName()
const char * TG4StepManager::CurrentVolOffName (Int_t off) const
Return the off-th mother's physical volume name.
Definition at line 461 of file TG4StepManager.cxx.
CurrentVolPath()
const char * TG4StepManager::CurrentVolPath ()
Return the current volume path.
Definition at line 480 of file TG4StepManager.cxx.
CurrentBoundaryNormal()
Bool_t TG4StepManager::CurrentBoundaryNormal (Double_t & x, Double_t & y, Double_t & z) const
Return the he normal vector of the surface of the last volume exited
Definition at line 515 of file TG4StepManager.cxx.
CurrentMaterial()
Int_t TG4StepManager::CurrentMaterial (Float_t & a, Float_t & z, Float_t & dens, Float_t & radl, Float_t & absl) const
Get parameters of the current material material during transport. Return the number of elements in the mixture
Parameters
a The atomic mass in au
z The atomic number
dens The density in g/cm3
radl The radiation length in cm
absl The absorption length in cm
Definition at line 539 of file TG4StepManager.cxx.
CurrentMedium()
Int_t TG4StepManager::CurrentMedium () const
Return the medium ID
Definition at line 572 of file TG4StepManager.cxx.
Gmtod() [1/2]
void TG4StepManager::Gmtod (Double_t * xm, Double_t * xd, Int_t iflag)
Transform a position from the world reference frame to the current volume reference frame.
Parameters
xm Known coordinates in the world reference system
xd Computed coordinates in the daughter reference system
iflag The option:
IFLAG=1 convert coordinates,
IFLAG=2 convert direction cosinus
Definition at line 607 of file TG4StepManager.cxx.
Referenced by Gmtod().
Gmtod() [2/2]
void TG4StepManager::Gmtod (Float_t * xm, Float_t * xd, Int_t iflag)
Transform a position from the world reference frame to the current volume reference frame.
Parameters
xm Known coordinates in the world reference system
xd Computed coordinates in the daughter reference system
iflag The option:
IFLAG=1 convert coordinates,
IFLAG=2 convert direction cosinus
Definition at line 581 of file TG4StepManager.cxx.
Gdtom() [1/2]
void TG4StepManager::Gdtom (Double_t * xd, Double_t * xm, Int_t iflag)
Transform a position from the current volume reference frame to the world reference frame.
Parameters
xd Known coordinates in the daughter reference system
xm Computed coordinates in the world reference system
iflag The option:
IFLAG=1 convert coordinates,
IFLAG=2 convert direction cosinus
Definition at line 672 of file TG4StepManager.cxx.
Referenced by Gdtom().
Gdtom() [2/2]
void TG4StepManager::Gdtom (Float_t * xd, Float_t * xm, Int_t iflag)
Transform a position from the current volume reference frame to the world reference frame.
Parameters
xd Known coordinates in the daughter reference system
xm Computed coordinates in the world reference system
iflag The option:
IFLAG=1 convert coordinates,
IFLAG=2 convert direction cosinus
Definition at line 647 of file TG4StepManager.cxx.
MaxStep()
Double_t TG4StepManager::MaxStep () const
Return the maximum step allowed in the current logical volume by user limits.
Definition at line 711 of file TG4StepManager.cxx.
GetMaxNStep()
Int_t TG4StepManager::GetMaxNStep () const
Return the maximum number of steps.
Definition at line 738 of file TG4StepManager.cxx.
TrackPosition() [1/3]
void TG4StepManager::TrackPosition (TLorentzVector & position) const
Fill the current particle position in the world reference frame and the global time since the event in which the track belongs is created. (position in the PostStepPoint).
Definition at line 746 of file TG4StepManager.cxx.
Referenced by TrackPosition().
TrackPosition() [2/3]
void TG4StepManager::TrackPosition (Double_t & x, Double_t & y, Double_t & z) const
Fill the current particle position in the world reference frame (position in the PostStepPoint).
Definition at line 775 of file TG4StepManager.cxx.
TrackPosition() [3/3]
void TG4StepManager::TrackPosition (Float_t & x, Float_t & y, Float_t & z) const
Fill the current particle position in the world reference frame (position in the PostStepPoint) as float.
Definition at line 801 of file TG4StepManager.cxx.
TrackMomentum() [1/3]
void TG4StepManager::TrackMomentum (TLorentzVector & momentum) const
Fill the current particle momentum (px, py, pz, Etot) Not updated in Gflash fast simulation.
Definition at line 815 of file TG4StepManager.cxx.
Referenced by TrackMomentum().
TrackMomentum() [2/3]
void TG4StepManager::TrackMomentum (Double_t & px, Double_t & py, Double_t & pz, Double_t & etot) const
Fill the current particle momentum Not updated in Gflash fast simulation.
Definition at line 834 of file TG4StepManager.cxx.
TrackMomentum() [3/3]
void TG4StepManager::TrackMomentum (Float_t & px, Float_t & py, Float_t & pz, Float_t & etot) const
Fill the current particle momentum as float. Not updated in Gflash fast simulation.
Definition at line 856 of file TG4StepManager.cxx.
TrackStep()
Double_t TG4StepManager::TrackStep () const
Return the current step length. Not updated in Gflash fast simulation.
Definition at line 872 of file TG4StepManager.cxx.
TrackLength()
Double_t TG4StepManager::TrackLength () const
Return the length of the current track from its origin. Not updated in Gflash fast simulation.
Definition at line 888 of file TG4StepManager.cxx.
TrackTime()
Double_t TG4StepManager::TrackTime () const
Return the global track time = time since the event in which the track belongs is created.
Note that in Geant4: there is also defined proper time as the proper time of the dynamical particle of the current track. Not updated in Gflash fast simulation.
Definition at line 904 of file TG4StepManager.cxx.
Edep()
Double_t TG4StepManager::Edep () const
Return the total energy deposit in this step.
Definition at line 920 of file TG4StepManager.cxx.
NIELEdep()
Double_t TG4StepManager::NIELEdep () const
Return the non-ionizing energy deposit in this step.
Definition at line 955 of file TG4StepManager.cxx.
StepNumber()
Int_t TG4StepManager::StepNumber () const
Return the current step number
Definition at line 973 of file TG4StepManager.cxx.
TrackWeight()
Double_t TG4StepManager::TrackWeight () const
Return the track weight
Definition at line 984 of file TG4StepManager.cxx.
TrackPolarization() [1/2]
void TG4StepManager::TrackPolarization (Double_t & polX, Double_t & polY, Double_t & polZ) const
Get the track polarization
Definition at line 992 of file TG4StepManager.cxx.
TrackPolarization() [2/2]
void TG4StepManager::TrackPolarization (TVector3 & pol) const
Get the track polarization
Definition at line 1004 of file TG4StepManager.cxx.
TrackPid()
Int_t TG4StepManager::TrackPid () const
Return the current particle PDG encoding.
Definition at line 1015 of file TG4StepManager.cxx.
TrackCharge()
Double_t TG4StepManager::TrackCharge () const
Return the current particle charge.
Definition at line 1044 of file TG4StepManager.cxx.
TrackMass()
Double_t TG4StepManager::TrackMass () const
Return the current particle mass at rest.
Definition at line 1057 of file TG4StepManager.cxx.
Etot()
Double_t TG4StepManager::Etot () const
Return the total energy of the current particle.
Definition at line 1070 of file TG4StepManager.cxx.
IsTrackInside()
Bool_t TG4StepManager::IsTrackInside () const
Return true if the particle does not cross a geometrical boundary and is not in the vertex.
Definition at line 1084 of file TG4StepManager.cxx.
IsTrackEntering()
Bool_t TG4StepManager::IsTrackEntering () const
Return true if the particle crosses a geometrical boundary or is in the vertex.
Definition at line 1098 of file TG4StepManager.cxx.
IsTrackExiting()
Bool_t TG4StepManager::IsTrackExiting () const
Return true if the particle crosses a geometrical boundary.
Definition at line 1112 of file TG4StepManager.cxx.
Referenced by IsTrackInside().
IsTrackOut()
Bool_t TG4StepManager::IsTrackOut () const
Return true if the particle crosses the world boundary at the post-step point.
Definition at line 1130 of file TG4StepManager.cxx.
IsTrackDisappeared()
Bool_t TG4StepManager::IsTrackDisappeared () const
Return true if particle has disappeared (due to any physical process) or has been killed or postponed to next event.
Definition at line 1180 of file TG4StepManager.cxx.
IsTrackStop()
Bool_t TG4StepManager::IsTrackStop () const
Return true if the particle has stopped or has been killed, suspended or postponed to the next event.
Possible track status from G4:
fAlive, // Continue the tracking
fStopButAlive, // Invoke active rest physics processes and // and kill the current track afterward
fStopAndKill, // Kill the current track
fKillTrackAndSecondaries, // Kill the current track and also associated // secondaries.
fSuspend, // Suspend the current track
fPostponeToNextEvent // Postpones the tracking of thecurrent track // to the next event.
Definition at line 1148 of file TG4StepManager.cxx.
IsTrackAlive()
Bool_t TG4StepManager::IsTrackAlive () const
Return true if particle continues tracking.
Definition at line 1201 of file TG4StepManager.cxx.
IsNewTrack()
Bool_t TG4StepManager::IsNewTrack () const
Return true when the track performs the first step.
Definition at line 1217 of file TG4StepManager.cxx.
NSecondaries()
Int_t TG4StepManager::NSecondaries () const
Return the number of secondary particles generated in the current step.
Definition at line 1228 of file TG4StepManager.cxx.
Referenced by GetSecondary(), and ProdProcess().
GetSecondary()
void TG4StepManager::GetSecondary (Int_t index, Int_t & particleId, TLorentzVector & position, TLorentzVector & momentum)
Fill the parameters of the generated secondary particle !! Check if indexing of secondaries is same !!
Parameters
index The secondary particle index
particleId The PDG encoding
position The position
momentum The momentum
Definition at line 1248 of file TG4StepManager.cxx.
ProdProcess()
TMCProcess TG4StepManager::ProdProcess (Int_t isec) const
Return the VMC code of the process that has produced the secondary particle specified by its index
Definition at line 1303 of file TG4StepManager.cxx.
StepProcesses()
Int_t TG4StepManager::StepProcesses (TArrayI & proc) const
Fill the array of processes that were active in the current step. The array is filled with the process VMC codes (TMCProcess). Return the number of active processes (TBD: Distinguish between kPDeltaRay and kPEnergyLoss)
Definition at line 1357 of file TG4StepManager.cxx.
operator=()
TG4StepManager & TG4StepManager::operator= (const TG4StepManager & right) private
Not implemented.
CheckTrack()
void TG4StepManager::CheckTrack () const private
Give exception in case the track is not defined.
Definition at line 97 of file TG4StepManager.cxx.
Referenced by Etot(), ForceDecayTime(), GetCurrentPhysicalVolume(), GetCurrentTouchable(), IsTrackAlive(), IsTrackDisappeared(), IsTrackStop(), TrackCharge(), TrackLength(), TrackMass(), TrackMomentum(), TrackMomentum(), TrackPid(), TrackPosition(), TrackPosition(), and TrackTime().
CheckStep()
void TG4StepManager::CheckStep (const G4String & method) const private
Give exception in case the step is not defined.
Definition at line 107 of file TG4StepManager.cxx.
Referenced by Edep(), IsTrackExiting(), IsTrackOut(), NIELEdep(), ProdProcess(), StepProcesses(), and TrackStep().
CheckGflashSpot()
void TG4StepManager::CheckGflashSpot (const G4String & method) const private
Give exception in case the step is not defined.
Definition at line 117 of file TG4StepManager.cxx.
Referenced by Edep().
CheckSteppingManager()
void TG4StepManager::CheckSteppingManager () const private
Give exception in case the step is not defined.
Definition at line 128 of file TG4StepManager.cxx.
Referenced by GetSecondary(), NSecondaries(), and StepProcesses().
SetTLorentzVector()
void TG4StepManager::SetTLorentzVector (G4ThreeVector xyz, G4double t, TLorentzVector & lv) const private
Fill TLorentzVector with G4ThreeVector and G4double.
Definition at line 138 of file TG4StepManager.cxx.
Referenced by GetSecondary(), TrackMomentum(), and TrackPosition().
GetCurrentTouchable()
const G4VTouchable * TG4StepManager::GetCurrentTouchable () const private
Return the current touchable.
Definition at line 150 of file TG4StepManager.cxx.
Referenced by CurrentVolPath(), Gdtom(), GetCurrentOffPhysicalVolume(), and Gmtod().
GetCurrentOffPhysicalVolume()
G4VPhysicalVolume * TG4StepManager::GetCurrentOffPhysicalVolume (G4int off, G4bool warn = false) const private
Return the physical volume of the off-th mother of the current volume.
Definition at line 170 of file TG4StepManager.cxx.
Referenced by CurrentVolOffID(), and CurrentVolOffName().
Member Data Documentation
fgInstance
G4ThreadLocal TG4StepManager * TG4StepManager::fgInstance = 0 static private
this instance
Definition at line 169 of file TG4StepManager.h.
Referenced by Instance(), TG4StepManager(), and ~TG4StepManager().
fTrack
G4Track* TG4StepManager::fTrack private
current track
Definition at line 175 of file TG4StepManager.h.
Referenced by CheckTrack(), Edep(), Etot(), ForceDecayTime(), GetCurrentPhysicalVolume(), GetCurrentTouchable(), GetTrack(), InterruptTrack(), IsTrackAlive(), IsTrackDisappeared(), IsTrackStop(), MaxStep(), SetStep(), SetStep(), SetStep(), StepNumber(), StopEvent(), StopTrack(), TG4StepManager(), TrackCharge(), TrackLength(), TrackMass(), TrackMomentum(), TrackMomentum(), TrackPid(), TrackPolarization(), TrackPolarization(), TrackPosition(), TrackPosition(), TrackTime(), and TrackWeight().
fStep
G4Step* TG4StepManager::fStep private
current step
Definition at line 178 of file TG4StepManager.h.
Referenced by CheckStep(), Edep(), GetStep(), IsTrackExiting(), IsTrackOut(), NIELEdep(), ProdProcess(), SetStep(), SetStep(), SetStep(), StepProcesses(), TG4StepManager(), and TrackStep().
fGflashSpot
G4GFlashSpot* TG4StepManager::fGflashSpot private
current Gflash spot
Definition at line 181 of file TG4StepManager.h.
Referenced by CheckGflashSpot(), Edep(), GetCurrentPhysicalVolume(), GetCurrentTouchable(), SetStep(), SetStep(), SetStep(), TG4StepManager(), TrackPosition(), and TrackPosition().
fStepStatus
TG4StepStatus TG4StepManager::fStepStatus private
step status
that decides whether track properties will be returned from PreStepPoint or PostStepPoint
Definition at line 186 of file TG4StepManager.h.
Referenced by Edep(), GetCurrentPhysicalVolume(), GetCurrentTouchable(), GetStepStatus(), IsNewTrack(), IsTrackEntering(), IsTrackExiting(), IsTrackInside(), IsTrackOut(), NIELEdep(), NSecondaries(), ProdProcess(), SetStep(), SetStep(), SetStep(), StepProcesses(), TG4StepManager(), TrackPosition(), TrackPosition(), and TrackStep().
fLimitsModifiedOnFly
TG4Limits* TG4StepManager::fLimitsModifiedOnFly private
limits which step limit was modified during tracking
Definition at line 189 of file TG4StepManager.h.
Referenced by GetLimitsModifiedOnFly(), SetMaxStep(), SetMaxStepBack(), and TG4StepManager().
fSteppingManager
G4SteppingManager* TG4StepManager::fSteppingManager private
G4SteppingManager.
Definition at line 192 of file TG4StepManager.h.
Referenced by CheckSteppingManager(), Edep(), GetSecondary(), NSecondaries(), ProdProcess(), SetSteppingManager(), and TG4StepManager().
fNameBuffer
G4String TG4StepManager::fNameBuffer mutable private
buffer for current volume name or path
Definition at line 195 of file TG4StepManager.h.
Referenced by CurrentVolName(), CurrentVolOffName(), CurrentVolPath(), and TG4StepManager().
fCopyNoOffset
G4int TG4StepManager::fCopyNoOffset private
volume copy number offset
Definition at line 198 of file TG4StepManager.h.
Referenced by CurrentVolID(), CurrentVolOffID(), and TG4StepManager().
fDivisionCopyNoOffset
G4int TG4StepManager::fDivisionCopyNoOffset private
division copy number offset
Definition at line 201 of file TG4StepManager.h.
Referenced by CurrentVolID(), CurrentVolOffID(), and TG4StepManager().
fTrackManager
TG4TrackManager* TG4StepManager::fTrackManager private
Cached pointer to thread-local track manager.
Definition at line 204 of file TG4StepManager.h.
Referenced by ForceDecayTime(), InterruptTrack(), LateInitialize(), TG4StepManager(), and TrackPid().
fInitialVMCTrackStatus
TMCParticleStatus* TG4StepManager::fInitialVMCTrackStatus private
The initial status of a VMC track when it was popped from the VMC stack.
Definition at line 207 of file TG4StepManager.h.
Referenced by SetInitialVMCTrackStatus(), StepNumber(), TG4StepManager(), and TrackLength().
The documentation for this class was generated from the following files:
source/digits+hits/include/TG4StepManager.h
source/digits+hits/src/TG4StepManager.cxx