Geant4 VMC: TG4Medium Class Reference
TG4Medium Class Reference
geometry
Helper class to keep medium data.
#include <TG4Medium.h>
Public Member Functions
TG4Medium (G4int id)
~TG4Medium ()
void Print () const
void SetName (const G4String &name)
void SetMaterial (G4Material *material)
void SetLimits (G4UserLimits *limits)
void SetIfield (G4int ifield)
G4int GetID () const
G4String GetName () const
G4Material * GetMaterial () const
G4UserLimits * GetLimits () const
G4int GetIfield () const
Private Member Functions
TG4Medium ()
Not implemented.
TG4Medium (const TG4Medium &right)
Not implemented.
TG4Medium & operator= (const TG4Medium &right)
Not implemented.
Private Attributes
G4int fID
medium ID
G4String fName
medium name
G4Material * fMaterial
material associated with this medium
G4UserLimits * fLimits
user limits associated with this medium
G4int fIfield
Static Private Attributes
static const G4String fgkUndefinedName = "UndefinedMediumName"
the default (undefined) name
static const G4int fgkDefaultIfield = 1
the default ifield value
Detailed Description
Helper class to keep medium data.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 28 of file TG4Medium.h.
Constructor & Destructor Documentation
TG4Medium() [1/3]
TG4Medium::TG4Medium (G4int id)
Standard constructor from given id
Definition at line 27 of file TG4Medium.cxx.
Referenced by operator=(), and TG4Medium().
~TG4Medium()
TG4Medium::~TG4Medium ()
Destructor
Definition at line 38 of file TG4Medium.cxx.
TG4Medium() [2/3]
TG4Medium::TG4Medium () private
Not implemented.
TG4Medium() [3/3]
TG4Medium::TG4Medium (const TG4Medium & right) private
Not implemented.
Member Function Documentation
Print()
void TG4Medium::Print () const
Print medium characteristics
Definition at line 44 of file TG4Medium.cxx.
SetName()
void TG4Medium::SetName (const G4String & name)
Set the given name; give a warning if medium name has been already defined
Definition at line 55 of file TG4Medium.cxx.
Referenced by TG4GeometryManager::FillMediumMapFromG4(), and TG4GeometryManager::FillMediumMapFromRoot().
SetMaterial()
void TG4Medium::SetMaterial (G4Material * material)
Set the given material; give a warning if medium material has been already defined
Definition at line 68 of file TG4Medium.cxx.
Referenced by TG4GeometryManager::FillMediumMapFromG3(), TG4GeometryManager::FillMediumMapFromG4(), and TG4GeometryManager::FillMediumMapFromRoot().
SetLimits()
void TG4Medium::SetLimits (G4UserLimits * limits)
Set the given limits;
Definition at line 83 of file TG4Medium.cxx.
Referenced by TG4GeometryManager::FillMediumMapFromG3(), TG4GeometryManager::FillMediumMapFromRoot(), TG4PhysicsManager::GstparControl(), TG4PhysicsManager::GstparCut(), and TG4GeometryManager::SetUserLimits().
SetIfield()
void TG4Medium::SetIfield (G4int ifield) inline
Set G3 tracking medium parameter 'ifield'
Definition at line 79 of file TG4Medium.h.
Referenced by TG4GeometryManager::FillMediumMapFromRoot().
GetID()
G4int TG4Medium::GetID () const inline
Return ID
Definition at line 84 of file TG4Medium.h.
Referenced by TG4GeometryServices::GetMediumId(), and TG4MCGeometry::MediumId().
GetName()
G4String TG4Medium::GetName () const inline
Return name
Definition at line 89 of file TG4Medium.h.
Referenced by TG4GeometryServices::FindLimits(), and TG4GeometryManager::SetUserLimits().
GetMaterial()
G4Material * TG4Medium::GetMaterial () const inline
Return material
Definition at line 94 of file TG4Medium.h.
Referenced by TG4RegionsManager::DefineRegions(), TG4OpGeometryManager::SetCerenkov(), TG4OpGeometryManager::SetMaterialProperty(), and TG4OpGeometryManager::SetMaterialProperty().
GetLimits()
G4UserLimits * TG4Medium::GetLimits () const inline
Return user limits
Definition at line 99 of file TG4Medium.h.
Referenced by TG4PhysicsManager::GstparControl(), TG4PhysicsManager::GstparCut(), TG4GeometryServices::PrintControls(), TG4GeometryServices::PrintCuts(), and TG4GeometryManager::SetUserLimits().
GetIfield()
G4int TG4Medium::GetIfield () const inline
Return G3 tracking medium parameter 'ifield'
Definition at line 104 of file TG4Medium.h.
Referenced by TG4GeometryManager::ConstructZeroFields().
operator=()
TG4Medium & TG4Medium::operator= (const TG4Medium & right) private
Not implemented.
Member Data Documentation
fgkUndefinedName
const G4String TG4Medium::fgkUndefinedName = "UndefinedMediumName" static private
the default (undefined) name
Definition at line 59 of file TG4Medium.h.
Referenced by SetName(), and TG4Medium().
fgkDefaultIfield
const G4int TG4Medium::fgkDefaultIfield = 1 static private
the default ifield value
Definition at line 60 of file TG4Medium.h.
Referenced by TG4Medium().
fID
G4int TG4Medium::fID private
medium ID
Definition at line 63 of file TG4Medium.h.
Referenced by GetID(), Print(), and TG4Medium().
fName
G4String TG4Medium::fName private
medium name
Definition at line 64 of file TG4Medium.h.
Referenced by GetName(), Print(), SetName(), and TG4Medium().
fMaterial
G4Material* TG4Medium::fMaterial private
material associated with this medium
Definition at line 65 of file TG4Medium.h.
Referenced by GetMaterial(), SetMaterial(), and TG4Medium().
fLimits
G4UserLimits* TG4Medium::fLimits private
user limits associated with this medium
Definition at line 66 of file TG4Medium.h.
Referenced by GetLimits(), Print(), SetLimits(), and TG4Medium().
fIfield
G4int TG4Medium::fIfield private
G3 tracking medium parameter 'ifield'
0 no magnetic field
-1 user decision in guswim
1 tracking performed with Runge Kutta
2 tracking performed with helix
3 constant magnetic field along z
Definition at line 74 of file TG4Medium.h.
Referenced by GetIfield(), SetIfield(), and TG4Medium().
The documentation for this class was generated from the following files:
source/geometry/include/TG4Medium.h
source/geometry/src/TG4Medium.cxx