Geant4 VMC: TG4FieldParameters Class Reference
TG4FieldParameters Class Reference
geometry
The magnetic field parameters.
#include <TG4FieldParameters.h>
Public Member Functions
TG4FieldParameters (const G4String &volumeName="")
~TG4FieldParameters ()
void PrintParameters () const
void SetFieldType (FieldType field)
Set type of field.
void SetEquationType (EquationType equation)
Set the type of equation of motion of a particle in a field.
void SetStepperType (StepperType stepper)
Set the type of integrator of particle's equation of motion.
void SetUserEquationOfMotion (G4EquationOfMotion *equation)
void SetUserStepper (G4MagIntegratorStepper *stepper)
void SetStepMinimum (G4double value)
Set minimum step in G4ChordFinder.
void SetDeltaChord (G4double value)
Set delta chord in G4ChordFinder.
void SetDeltaOneStep (G4double value)
Set delta one step in global field manager.
void SetDeltaIntersection (G4double value)
Set delta intersection in global field manager.
void SetMinimumEpsilonStep (G4double value)
Set minimum epsilon step in global field manager.
void SetMaximumEpsilonStep (G4double value)
Set maximum epsilon step in global field manager.
void SetConstDistance (G4double value)
Set the distance within which the field is considered constant.
void SetIsMonopole (G4bool isMonopole)
G4String GetVolumeName () const
Return the name of associated volume, if local field.
FieldType GetFieldType () const
Return the type of field.
EquationType GetEquationType () const
Return the type of equation of motion of a particle in a field.
StepperType GetStepperType () const
Return the type of integrator of particle's equation of motion.
G4EquationOfMotion * GetUserEquationOfMotion () const
Return the user defined equation of motion.
G4MagIntegratorStepper * GetUserStepper () const
Return the user defined integrator of particle's equation of motion.
G4double GetStepMinimum () const
Return minimum step in G4ChordFinder.
G4double GetDeltaChord () const
Return delta chord in G4ChordFinder.
G4double GetDeltaOneStep () const
Return delta one step in global field manager.
G4double GetDeltaIntersection () const
Return delta intersection in global field manager.
G4double GetMinimumEpsilonStep () const
Return minimum epsilon step in global field manager.
G4double GetMaximumEpsilonStep () const
Return maximum epsilon step in global field manager.
G4double GetConstDistance () const
Return the distance within which the field is considered constant.
G4bool GetIsMonopole () const
Static Public Member Functions
static G4String FieldTypeName (FieldType field)
static G4String EquationTypeName (EquationType equation)
static G4String StepperTypeName (StepperType stepper)
static FieldType GetFieldType (const G4String &name)
static EquationType GetEquationType (const G4String &name)
static StepperType GetStepperType (const G4String &name)
Private Attributes
TG4FieldParametersMessenger * fMessenger
Messenger for this class.
G4String fVolumeName
The name of associated volume, if local field.
G4double fStepMinimum
Minimum step in G4ChordFinder.
G4double fDeltaChord
Delta chord in G4ChordFinder.
G4double fDeltaOneStep
Delta one step in global field manager.
G4double fDeltaIntersection
Delta intersection in global field manager.
G4double fMinimumEpsilonStep
Minimum epsilon step in global field manager.
G4double fMaximumEpsilonStep
Maximum epsilon step in global field manager.
FieldType fField
Type of field.
EquationType fEquation
Type of equation of motion of a particle in a field.
StepperType fStepper
Type of integrator of particle's equation of motion.
G4EquationOfMotion * fUserEquation
User defined equation of motion.
G4MagIntegratorStepper * fUserStepper
User defined integrator of particle's equation of motion.
G4double fConstDistance
The distance within which the field is considered constant.
G4bool fIsMonopole
Static Private Attributes
static const G4double fgkDefaultStepMinimum = 0.01 * mm
Default minimum step in G4ChordFinder.
static const G4double fgkDefaultDeltaChord = 0.25 * mm
Default delta chord in G4ChordFinder.
static const G4double fgkDefaultDeltaOneStep = 0.01 * mm
Default delta one step in global field manager.
static const G4double fgkDefaultDeltaIntersection = 0.001 * mm
Delta intersection in global field manager.
static const G4double fgkDefaultMinimumEpsilonStep = 5.0e-5
Default minimum epsilon step in global field manager.
static const G4double fgkDefaultMaximumEpsilonStep = 0.001
Default maximum epsilon step in global field manager.
static const G4double fgkDefaultConstDistance = 0.
Default constant distance.
Detailed Description
The magnetic field parameters.
The class defines the type of equation of motion of a particle in a field and the integration method, as well as other accuracy parameters.
The default values correspond to the defaults set in Geant4 (taken from Geant4 9.3 release.) As Geant4 classes to not provide access methods for these defaults, the defaults have to be checked with each new Geant4 release.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 106 of file TG4FieldParameters.h.
Constructor & Destructor Documentation
TG4FieldParameters()
TG4FieldParameters::TG4FieldParameters (const G4String & volumeName = "")
Default constructor
Definition at line 217 of file TG4FieldParameters.cxx.
~TG4FieldParameters()
TG4FieldParameters::~TG4FieldParameters ()
Destructor
Definition at line 240 of file TG4FieldParameters.cxx.
Member Function Documentation
PrintParameters()
void TG4FieldParameters::PrintParameters () const
Prints all customizable accuracy parameters
Definition at line 252 of file TG4FieldParameters.cxx.
FieldTypeName()
G4String TG4FieldParameters::FieldTypeName (FieldType field) static
Return the field type as a string
Definition at line 40 of file TG4FieldParameters.cxx.
Referenced by TG4GeometryManager::CreateField(), GetFieldType(), PrintParameters(), TG4FieldParametersMessenger::SetNewValue(), and TG4FieldParametersMessenger::TG4FieldParametersMessenger().
EquationTypeName()
G4String TG4FieldParameters::EquationTypeName (EquationType equation) static
Return the equation type as a string
Definition at line 59 of file TG4FieldParameters.cxx.
Referenced by GetEquationType(), PrintParameters(), TG4FieldParametersMessenger::SetNewValue(), and TG4FieldParametersMessenger::TG4FieldParametersMessenger().
StepperTypeName()
G4String TG4FieldParameters::StepperTypeName (StepperType stepper) static
Return the stepper type as a string
Definition at line 84 of file TG4FieldParameters.cxx.
Referenced by TG4GeometryManager::CreateField(), GetStepperType(), PrintParameters(), TG4FieldParametersMessenger::SetNewValue(), and TG4FieldParametersMessenger::TG4FieldParametersMessenger().
GetFieldType() [1/2]
FieldType TG4FieldParameters::GetFieldType (const G4String & name) static
Return the field type for given field type name
Definition at line 147 of file TG4FieldParameters.cxx.
Referenced by TG4GeometryManager::CreateField(), TG4Field::CreateG4Field(), and TG4Field::Update().
GetEquationType() [1/2]
EquationType TG4FieldParameters::GetEquationType (const G4String & name) static
Return the equation type for given equation type name
Definition at line 161 of file TG4FieldParameters.cxx.
Referenced by TG4Field::Update().
GetStepperType() [1/2]
StepperType TG4FieldParameters::GetStepperType (const G4String & name) static
Return the stepper type for given stepper type name
Definition at line 178 of file TG4FieldParameters.cxx.
Referenced by TG4GeometryManager::CreateField(), and TG4Field::Update().
SetFieldType()
void TG4FieldParameters::SetFieldType (FieldType field) inline
Set type of field.
Definition at line 221 of file TG4FieldParameters.h.
SetEquationType()
void TG4FieldParameters::SetEquationType (EquationType equation) inline
Set the type of equation of motion of a particle in a field.
Definition at line 227 of file TG4FieldParameters.h.
SetStepperType()
void TG4FieldParameters::SetStepperType (StepperType stepper) inline
Set the type of integrator of particle's equation of motion.
Definition at line 233 of file TG4FieldParameters.h.
SetUserEquationOfMotion()
void TG4FieldParameters::SetUserEquationOfMotion (G4EquationOfMotion * equation)
Set user defined equation of motion
Definition at line 274 of file TG4FieldParameters.cxx.
Referenced by TG4GeometryManager::SetUserEquationOfMotion().
SetUserStepper()
void TG4FieldParameters::SetUserStepper (G4MagIntegratorStepper * stepper)
Set user defined integrator of particle's equation of motion
Definition at line 283 of file TG4FieldParameters.cxx.
Referenced by TG4GeometryManager::SetUserStepper().
SetStepMinimum()
void TG4FieldParameters::SetStepMinimum (G4double value) inline
Set minimum step in G4ChordFinder.
Definition at line 239 of file TG4FieldParameters.h.
SetDeltaChord()
void TG4FieldParameters::SetDeltaChord (G4double value) inline
Set delta chord in G4ChordFinder.
Definition at line 245 of file TG4FieldParameters.h.
SetDeltaOneStep()
void TG4FieldParameters::SetDeltaOneStep (G4double value) inline
Set delta one step in global field manager.
Definition at line 251 of file TG4FieldParameters.h.
SetDeltaIntersection()
void TG4FieldParameters::SetDeltaIntersection (G4double value) inline
Set delta intersection in global field manager.
Definition at line 257 of file TG4FieldParameters.h.
SetMinimumEpsilonStep()
void TG4FieldParameters::SetMinimumEpsilonStep (G4double value) inline
Set minimum epsilon step in global field manager.
Definition at line 263 of file TG4FieldParameters.h.
SetMaximumEpsilonStep()
void TG4FieldParameters::SetMaximumEpsilonStep (G4double value) inline
Set maximum epsilon step in global field manager.
Definition at line 269 of file TG4FieldParameters.h.
SetConstDistance()
void TG4FieldParameters::SetConstDistance (G4double value) inline
Set the distance within which the field is considered constant.
Definition at line 275 of file TG4FieldParameters.h.
SetIsMonopole()
void TG4FieldParameters::SetIsMonopole (G4bool isMonopole) inline
Set the option to create an extra monopole field integrator which will be activated directly by G4MonopoleTransportation
Definition at line 282 of file TG4FieldParameters.h.
GetVolumeName()
G4String TG4FieldParameters::GetVolumeName () const inline
Return the name of associated volume, if local field.
Definition at line 288 of file TG4FieldParameters.h.
Referenced by TG4FieldParametersMessenger::TG4FieldParametersMessenger().
GetFieldType() [2/2]
FieldType TG4FieldParameters::GetFieldType () const inline
Return the type of field.
Definition at line 294 of file TG4FieldParameters.h.
GetEquationType() [2/2]
EquationType TG4FieldParameters::GetEquationType () const inline
Return the type of equation of motion of a particle in a field.
Definition at line 297 of file TG4FieldParameters.h.
GetStepperType() [2/2]
StepperType TG4FieldParameters::GetStepperType () const inline
Return the type of integrator of particle's equation of motion.
Definition at line 303 of file TG4FieldParameters.h.
GetUserEquationOfMotion()
G4EquationOfMotion * TG4FieldParameters::GetUserEquationOfMotion () const inline
Return the user defined equation of motion.
Definition at line 309 of file TG4FieldParameters.h.
Referenced by TG4Field::Update().
GetUserStepper()
G4MagIntegratorStepper * TG4FieldParameters::GetUserStepper () const inline
Return the user defined integrator of particle's equation of motion.
Definition at line 315 of file TG4FieldParameters.h.
Referenced by TG4Field::Update().
GetStepMinimum()
G4double TG4FieldParameters::GetStepMinimum () const inline
Return minimum step in G4ChordFinder.
Definition at line 321 of file TG4FieldParameters.h.
Referenced by TG4Field::Update().
GetDeltaChord()
G4double TG4FieldParameters::GetDeltaChord () const inline
Return delta chord in G4ChordFinder.
Definition at line 327 of file TG4FieldParameters.h.
Referenced by TG4Field::Update().
GetDeltaOneStep()
G4double TG4FieldParameters::GetDeltaOneStep () const inline
Return delta one step in global field manager.
Definition at line 333 of file TG4FieldParameters.h.
Referenced by TG4Field::Update().
GetDeltaIntersection()
G4double TG4FieldParameters::GetDeltaIntersection () const inline
Return delta intersection in global field manager.
Definition at line 339 of file TG4FieldParameters.h.
Referenced by TG4Field::Update().
GetMinimumEpsilonStep()
G4double TG4FieldParameters::GetMinimumEpsilonStep () const inline
Return minimum epsilon step in global field manager.
Definition at line 345 of file TG4FieldParameters.h.
Referenced by TG4Field::Update().
GetMaximumEpsilonStep()
G4double TG4FieldParameters::GetMaximumEpsilonStep () const inline
Return maximum epsilon step in global field manager.
Definition at line 351 of file TG4FieldParameters.h.
Referenced by TG4Field::Update().
GetConstDistance()
G4double TG4FieldParameters::GetConstDistance () const inline
Return the distance within which the field is considered constant.
Definition at line 357 of file TG4FieldParameters.h.
Referenced by TG4GeometryManager::CreateField(), and TG4Field::CreateG4Field().
GetIsMonopole()
G4bool TG4FieldParameters::GetIsMonopole () const inline
Return the option to create an extra monopole field integrator which will be activated directly by G4MonopoleTransportation
Definition at line 364 of file TG4FieldParameters.h.
Member Data Documentation
fgkDefaultStepMinimum
const G4double TG4FieldParameters::fgkDefaultStepMinimum = 0.01 * mm static private
Default minimum step in G4ChordFinder.
Definition at line 160 of file TG4FieldParameters.h.
Referenced by TG4FieldParameters().
fgkDefaultDeltaChord
const G4double TG4FieldParameters::fgkDefaultDeltaChord = 0.25 * mm static private
Default delta chord in G4ChordFinder.
Definition at line 162 of file TG4FieldParameters.h.
Referenced by TG4FieldParameters().
fgkDefaultDeltaOneStep
const G4double TG4FieldParameters::fgkDefaultDeltaOneStep = 0.01 * mm static private
Default delta one step in global field manager.
Definition at line 164 of file TG4FieldParameters.h.
Referenced by TG4FieldParameters().
fgkDefaultDeltaIntersection
const G4double TG4FieldParameters::fgkDefaultDeltaIntersection = 0.001 * mm static private
Delta intersection in global field manager.
Definition at line 166 of file TG4FieldParameters.h.
Referenced by TG4FieldParameters().
fgkDefaultMinimumEpsilonStep
const G4double TG4FieldParameters::fgkDefaultMinimumEpsilonStep = 5.0e-5 static private
Default minimum epsilon step in global field manager.
Definition at line 168 of file TG4FieldParameters.h.
Referenced by TG4FieldParameters().
fgkDefaultMaximumEpsilonStep
const G4double TG4FieldParameters::fgkDefaultMaximumEpsilonStep = 0.001 static private
Default maximum epsilon step in global field manager.
Definition at line 170 of file TG4FieldParameters.h.
Referenced by TG4FieldParameters().
fgkDefaultConstDistance
const G4double TG4FieldParameters::fgkDefaultConstDistance = 0. static private
Default constant distance.
Definition at line 172 of file TG4FieldParameters.h.
fMessenger
TG4FieldParametersMessenger* TG4FieldParameters::fMessenger private
Messenger for this class.
Definition at line 177 of file TG4FieldParameters.h.
Referenced by TG4FieldParameters(), and ~TG4FieldParameters().
fVolumeName
G4String TG4FieldParameters::fVolumeName private
The name of associated volume, if local field.
Definition at line 180 of file TG4FieldParameters.h.
Referenced by GetVolumeName(), PrintParameters(), and TG4FieldParameters().
fStepMinimum
G4double TG4FieldParameters::fStepMinimum private
Minimum step in G4ChordFinder.
Definition at line 183 of file TG4FieldParameters.h.
Referenced by GetStepMinimum(), PrintParameters(), SetStepMinimum(), and TG4FieldParameters().
fDeltaChord
G4double TG4FieldParameters::fDeltaChord private
Delta chord in G4ChordFinder.
Definition at line 185 of file TG4FieldParameters.h.
Referenced by GetDeltaChord(), PrintParameters(), SetDeltaChord(), and TG4FieldParameters().
fDeltaOneStep
G4double TG4FieldParameters::fDeltaOneStep private
Delta one step in global field manager.
Definition at line 187 of file TG4FieldParameters.h.
Referenced by GetDeltaOneStep(), PrintParameters(), SetDeltaOneStep(), and TG4FieldParameters().
fDeltaIntersection
G4double TG4FieldParameters::fDeltaIntersection private
Delta intersection in global field manager.
Definition at line 189 of file TG4FieldParameters.h.
Referenced by GetDeltaIntersection(), PrintParameters(), SetDeltaIntersection(), and TG4FieldParameters().
fMinimumEpsilonStep
G4double TG4FieldParameters::fMinimumEpsilonStep private
Minimum epsilon step in global field manager.
Definition at line 191 of file TG4FieldParameters.h.
Referenced by GetMinimumEpsilonStep(), PrintParameters(), SetMinimumEpsilonStep(), and TG4FieldParameters().
fMaximumEpsilonStep
G4double TG4FieldParameters::fMaximumEpsilonStep private
Maximum epsilon step in global field manager.
Definition at line 193 of file TG4FieldParameters.h.
Referenced by GetMaximumEpsilonStep(), PrintParameters(), SetMaximumEpsilonStep(), and TG4FieldParameters().
fField
FieldType TG4FieldParameters::fField private
Type of field.
Definition at line 196 of file TG4FieldParameters.h.
Referenced by GetFieldType(), PrintParameters(), SetFieldType(), and TG4FieldParameters().
fEquation
EquationType TG4FieldParameters::fEquation private
Type of equation of motion of a particle in a field.
Definition at line 199 of file TG4FieldParameters.h.
Referenced by GetEquationType(), PrintParameters(), SetEquationType(), SetUserEquationOfMotion(), and TG4FieldParameters().
fStepper
StepperType TG4FieldParameters::fStepper private
Type of integrator of particle's equation of motion.
Definition at line 202 of file TG4FieldParameters.h.
Referenced by GetStepperType(), PrintParameters(), SetStepperType(), SetUserStepper(), and TG4FieldParameters().
fUserEquation
G4EquationOfMotion* TG4FieldParameters::fUserEquation private
User defined equation of motion.
Definition at line 205 of file TG4FieldParameters.h.
Referenced by GetUserEquationOfMotion(), SetUserEquationOfMotion(), and TG4FieldParameters().
fUserStepper
G4MagIntegratorStepper* TG4FieldParameters::fUserStepper private
User defined integrator of particle's equation of motion.
Definition at line 208 of file TG4FieldParameters.h.
Referenced by GetUserStepper(), SetUserStepper(), and TG4FieldParameters().
fConstDistance
G4double TG4FieldParameters::fConstDistance private
The distance within which the field is considered constant.
Definition at line 211 of file TG4FieldParameters.h.
Referenced by GetConstDistance(), PrintParameters(), SetConstDistance(), and TG4FieldParameters().
fIsMonopole
G4bool TG4FieldParameters::fIsMonopole private
An option to create an extra monopole field integrator which will be activated directly by G4MonopoleTransportation
Definition at line 215 of file TG4FieldParameters.h.
Referenced by GetIsMonopole(), PrintParameters(), SetIsMonopole(), and TG4FieldParameters().
The documentation for this class was generated from the following files:
source/geometry/include/TG4FieldParameters.h
source/geometry/src/TG4FieldParameters.cxx