Geant4 VMC: TG4VPhysicsConstructor Class Reference
TG4VPhysicsConstructor Class Reference abstract
physics
Abstract base class for physics constructors with verbose.
#include <TG4VPhysicsConstructor.h>
Public Member Functions
TG4VPhysicsConstructor (const G4String &name)
TG4VPhysicsConstructor (const G4String &name, G4int theVerboseLevel)
virtual ~TG4VPhysicsConstructor ()
virtual void ConstructParticle ()=0
Construct particles.
virtual void ConstructProcess ()=0
Construct physics processes.
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
Protected Member Functions
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Private Member Functions
TG4VPhysicsConstructor ()
Not implemented.
TG4VPhysicsConstructor (const TG4VPhysicsConstructor &right)
Not implemented.
Detailed Description
Abstract base class for physics constructors with verbose.
Author
I. Hrivnacova; IPN Orsay
Definition at line 28 of file TG4VPhysicsConstructor.h.
Constructor & Destructor Documentation
TG4VPhysicsConstructor() [1/4]
TG4VPhysicsConstructor::TG4VPhysicsConstructor (const G4String & name)
Standard constructor
Definition at line 22 of file TG4VPhysicsConstructor.cxx.
Referenced by TG4EmModelPhysics::TG4EmModelPhysics(), TG4EmModelPhysics::TG4EmModelPhysics(), TG4ExtDecayerPhysics::TG4ExtDecayerPhysics(), TG4ExtDecayerPhysics::TG4ExtDecayerPhysics(), TG4FastSimulationPhysics::TG4FastSimulationPhysics(), TG4FastSimulationPhysics::TG4FastSimulationPhysics(), TG4ProcessMapPhysics::TG4ProcessMapPhysics(), TG4ProcessMapPhysics::TG4ProcessMapPhysics(), TG4SpecialCutsPhysics::TG4SpecialCutsPhysics(), TG4SpecialCutsPhysics::TG4SpecialCutsPhysics(), TG4StackPopperPhysics::TG4StackPopperPhysics(), TG4StackPopperPhysics::TG4StackPopperPhysics(), TG4StepLimiterPhysics::TG4StepLimiterPhysics(), TG4StepLimiterPhysics::TG4StepLimiterPhysics(), TG4TransitionRadiationPhysics::TG4TransitionRadiationPhysics(), TG4TransitionRadiationPhysics::TG4TransitionRadiationPhysics(), TG4UserParticlesPhysics::TG4UserParticlesPhysics(), TG4UserParticlesPhysics::TG4UserParticlesPhysics(), and TG4VPhysicsConstructor().
TG4VPhysicsConstructor() [2/4]
TG4VPhysicsConstructor::TG4VPhysicsConstructor (const G4String & name, G4int theVerboseLevel)
Standard constructor
Definition at line 31 of file TG4VPhysicsConstructor.cxx.
~TG4VPhysicsConstructor()
TG4VPhysicsConstructor::~TG4VPhysicsConstructor () virtual
Destructor
Definition at line 41 of file TG4VPhysicsConstructor.cxx.
TG4VPhysicsConstructor() [3/4]
TG4VPhysicsConstructor::TG4VPhysicsConstructor () private
Not implemented.
TG4VPhysicsConstructor() [4/4]
TG4VPhysicsConstructor::TG4VPhysicsConstructor (const TG4VPhysicsConstructor & right) private
Not implemented.
Member Function Documentation
ConstructParticle()
virtual void TG4VPhysicsConstructor::ConstructParticle () pure virtual
Construct particles.
Implemented in TG4EmModelPhysics, TG4ExtDecayerPhysics, TG4FastSimulationPhysics, TG4ProcessMapPhysics, TG4SpecialCutsPhysics, TG4StackPopperPhysics, TG4StepLimiterPhysics, TG4TransitionRadiationPhysics, and TG4UserParticlesPhysics.
ConstructProcess()
virtual void TG4VPhysicsConstructor::ConstructProcess () pure virtual
Construct physics processes.
Implemented in TG4EmModelPhysics, TG4ExtDecayerPhysics, TG4FastSimulationPhysics, TG4ProcessMapPhysics, TG4SpecialCutsPhysics, TG4StackPopperPhysics, TG4StepLimiterPhysics, TG4TransitionRadiationPhysics, and TG4UserParticlesPhysics.
VerboseLevel() [1/2]
void TG4VPhysicsConstructor::VerboseLevel (G4int level) protected virtual
Set the same value to G4VPhysicsConstructor verbose level and TG4Verbose level.
Reimplemented from TG4Verbose.
Definition at line 51 of file TG4VPhysicsConstructor.cxx.
VerboseLevel() [2/2]
G4int TG4VPhysicsConstructor::VerboseLevel () const protected virtual
Return TG4Verbose level value.
Reimplemented from TG4Verbose.
Definition at line 63 of file TG4VPhysicsConstructor.cxx.
Referenced by TG4FastSimulationPhysics::AddFastSimulationProcess(), TG4EmModelPhysics::AddModel(), TG4EmModelPhysics::AddModels(), TG4EmModelPhysics::ConstructProcess(), TG4ExtDecayerPhysics::ConstructProcess(), TG4FastSimulationPhysics::ConstructProcess(), TG4ProcessMapPhysics::ConstructProcess(), TG4SpecialCutsPhysics::ConstructProcess(), TG4StackPopperPhysics::ConstructProcess(), TG4StepLimiterPhysics::ConstructProcess(), TG4TransitionRadiationPhysics::ConstructProcess(), TG4UserParticlesPhysics::ConstructProcess(), TG4TransitionRadiationPhysics::CreateXTRProcess(), TG4EmModelPhysics::TG4EmModelPhysics(), TG4EmModelPhysics::TG4EmModelPhysics(), TG4VPhysicsConstructor(), TG4VPhysicsConstructor(), and TG4FastSimulationPhysics::UpdateRegions().
The documentation for this class was generated from the following files:
source/physics/include/TG4VPhysicsConstructor.h
source/physics/src/TG4VPhysicsConstructor.cxx