Geant4 VMC: TG4SpecialPhysicsList Class Reference
TG4SpecialPhysicsList Class Reference
physics_list
The Geant4 VMC special physics list helper class.
#include <TG4SpecialPhysicsList.h>
Public Member Functions
TG4SpecialPhysicsList (const G4String &selection)
TG4SpecialPhysicsList ()
virtual ~TG4SpecialPhysicsList ()
virtual void ConstructProcess ()
virtual void SetCuts ()
No cuts are set here.
virtual G4int VerboseLevel () const
virtual void VerboseLevel (G4int level)
void SetUserFastSimulation (TG4VUserFastSimulation *fastSimulation)
G4bool IsSpecialCuts () const
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
Static Public Member Functions
static TG4SpecialPhysicsList * Instance ()
static G4String AvailableSelections ()
static G4bool IsAvailableSelection (const G4String &selection)
Protected Attributes
TG4StackPopperPhysics * fStackPopperPhysics
Stack popper physics builder.
TG4TransitionRadiationPhysics * fTransitionRadiationPhysics
Transition radiation physics builder.
TG4EmModelPhysics * fEmModelPhysics
EM models physics builder.
TG4FastSimulationPhysics * fFastSimulationPhysics
Fast simulation physics builder.
G4bool fIsSpecialCuts
Option for special cuts.
Private Member Functions
TG4SpecialPhysicsList (const TG4SpecialPhysicsList &right)
Not implemented.
TG4SpecialPhysicsList & operator= (const TG4SpecialPhysicsList &right)
Not implemented.
void Configure (const G4String &selection)
Static Private Attributes
static G4ThreadLocal TG4SpecialPhysicsList * fgInstance = 0
this instance
Detailed Description
The Geant4 VMC special physics list helper class.
The special physics list instatiates the Geant4 VMC special processes according to the selection passed in the constructor
Author
I. Hrivnacova; IPN Orsay
Definition at line 37 of file TG4SpecialPhysicsList.h.
Constructor & Destructor Documentation
TG4SpecialPhysicsList() [1/3]
TG4SpecialPhysicsList::TG4SpecialPhysicsList (const G4String & selection)
Standard constructor
Definition at line 82 of file TG4SpecialPhysicsList.cxx.
Referenced by Instance(), operator=(), and TG4SpecialPhysicsList().
TG4SpecialPhysicsList() [2/3]
TG4SpecialPhysicsList::TG4SpecialPhysicsList ()
Default constructor
Definition at line 106 of file TG4SpecialPhysicsList.cxx.
~TG4SpecialPhysicsList()
TG4SpecialPhysicsList::~TG4SpecialPhysicsList () virtual
Destructor
Definition at line 124 of file TG4SpecialPhysicsList.cxx.
TG4SpecialPhysicsList() [3/3]
TG4SpecialPhysicsList::TG4SpecialPhysicsList (const TG4SpecialPhysicsList & right) private
Not implemented.
Member Function Documentation
Instance()
TG4SpecialPhysicsList * TG4SpecialPhysicsList::Instance () inline static
Return this instance
Definition at line 96 of file TG4SpecialPhysicsList.h.
Referenced by TG4RunManager::ConfigureRunManager(), and TG4PhysicsManager::SetProcessActivation().
AvailableSelections()
G4String TG4SpecialPhysicsList::AvailableSelections () static
Return list of all available selections
Definition at line 48 of file TG4SpecialPhysicsList.cxx.
Referenced by IsAvailableSelection(), and TG4RunConfiguration::TG4RunConfiguration().
IsAvailableSelection()
G4bool TG4SpecialPhysicsList::IsAvailableSelection (const G4String & selection) static
Return list of all available selections
Definition at line 62 of file TG4SpecialPhysicsList.cxx.
Referenced by TG4RunConfiguration::TG4RunConfiguration().
ConstructProcess()
void TG4SpecialPhysicsList::ConstructProcess () virtual
Construct all processes.
Definition at line 195 of file TG4SpecialPhysicsList.cxx.
SetCuts()
virtual void TG4SpecialPhysicsList::SetCuts () inline virtual
No cuts are set here.
Definition at line 53 of file TG4SpecialPhysicsList.h.
VerboseLevel() [1/2]
G4int TG4SpecialPhysicsList::VerboseLevel () const virtual
Return verbose level (via TG4Verbose)
Reimplemented from TG4Verbose.
Definition at line 215 of file TG4SpecialPhysicsList.cxx.
Referenced by TG4SpecialPhysicsList().
VerboseLevel() [2/2]
void TG4SpecialPhysicsList::VerboseLevel (G4int level) virtual
Set the specified level to both TG4Verbose and G4VModularPhysicsList. The verbose level is also propagated to registered physics contructors.
Reimplemented from TG4Verbose.
Definition at line 223 of file TG4SpecialPhysicsList.cxx.
SetUserFastSimulation()
void TG4SpecialPhysicsList::SetUserFastSimulation (TG4VUserFastSimulation * fastSimulation)
Set user fast simulation
Definition at line 244 of file TG4SpecialPhysicsList.cxx.
Referenced by TG4RunManager::ConfigureRunManager().
IsSpecialCuts()
G4bool TG4SpecialPhysicsList::IsSpecialCuts () const inline
Return true if specialCuts are selected
Definition at line 102 of file TG4SpecialPhysicsList.h.
operator=()
TG4SpecialPhysicsList & TG4SpecialPhysicsList::operator= (const TG4SpecialPhysicsList & right) private
Not implemented.
Configure()
void TG4SpecialPhysicsList::Configure (const G4String & selection) private
Create the selected physics constructors and registeres them in the modular physics list.
Definition at line 139 of file TG4SpecialPhysicsList.cxx.
Referenced by TG4SpecialPhysicsList(), and TG4SpecialPhysicsList().
Member Data Documentation
fStackPopperPhysics
TG4StackPopperPhysics* TG4SpecialPhysicsList::fStackPopperPhysics protected
Stack popper physics builder.
Definition at line 67 of file TG4SpecialPhysicsList.h.
Referenced by Configure(), TG4SpecialPhysicsList(), and TG4SpecialPhysicsList().
fTransitionRadiationPhysics
TG4TransitionRadiationPhysics* TG4SpecialPhysicsList::fTransitionRadiationPhysics protected
Transition radiation physics builder.
Definition at line 70 of file TG4SpecialPhysicsList.h.
fEmModelPhysics
TG4EmModelPhysics* TG4SpecialPhysicsList::fEmModelPhysics protected
EM models physics builder.
Definition at line 73 of file TG4SpecialPhysicsList.h.
Referenced by Configure(), TG4SpecialPhysicsList(), and TG4SpecialPhysicsList().
fFastSimulationPhysics
TG4FastSimulationPhysics* TG4SpecialPhysicsList::fFastSimulationPhysics protected
Fast simulation physics builder.
Definition at line 76 of file TG4SpecialPhysicsList.h.
Referenced by Configure(), SetUserFastSimulation(), and TG4SpecialPhysicsList().
fIsSpecialCuts
G4bool TG4SpecialPhysicsList::fIsSpecialCuts protected
Option for special cuts.
Definition at line 79 of file TG4SpecialPhysicsList.h.
Referenced by Configure(), IsSpecialCuts(), TG4SpecialPhysicsList(), and TG4SpecialPhysicsList().
fgInstance
G4ThreadLocal TG4SpecialPhysicsList * TG4SpecialPhysicsList::fgInstance = 0 static private
this instance
Definition at line 91 of file TG4SpecialPhysicsList.h.
Referenced by Instance(), TG4SpecialPhysicsList(), and ~TG4SpecialPhysicsList().
The documentation for this class was generated from the following files:
source/physics_list/include/TG4SpecialPhysicsList.h
source/physics_list/src/TG4SpecialPhysicsList.cxx