Geant4 VMC: TG4Globals Class Reference
TG4Globals Class Reference
global
Basic types and functions of general use.
#include <TG4Globals.h>
Public Member Functions
~TG4Globals ()
Static Public Member Functions
static void Exception (const TString &className, const TString &methodName, const TString &text)
static void Warning (const TString &className, const TString &methodName, const TString &text)
static TString Endl ()
static void AppendNumberToString (G4String &string, G4int number)
static G4bool Compare (G4bool activation, TG4G3ControlValue controlValue)
static void PrintStars (G4bool emptyLineFirst)
static G4String Help ()
static G4String GetToken (Int_t i, const TString &s)
static G4bool Contains (const G4String &name, const G4String &nameList)
Private Member Functions
TG4Globals ()
Static Private Attributes
static const TString fgkEndl = "x\n"
Special endl.
static const char fgkTokenSeparator = '+'
Separator in GetToken() method.
Detailed Description
Basic types and functions of general use.
Class provides the basic types and functions of general use. It is protected from instantiating (only static data members and static methods are defined).
Author
I. Hrivnacova; IPN, Orsay
Definition at line 68 of file TG4Globals.h.
Constructor & Destructor Documentation
~TG4Globals()
TG4Globals::~TG4Globals ()
Destructor
Definition at line 23 of file TG4Globals.cxx.
TG4Globals()
TG4Globals::TG4Globals () private
Member Function Documentation
Exception()
void TG4Globals::Exception (const TString & className, const TString & methodName, const TString & text) static
Print error message end exit the program.
Definition at line 33 of file TG4Globals.cxx.
Referenced by TG4ParticlesManager::AddIon(), TG4SpecialControlsV2::ApplyControls(), TG4ActionInitialization::Build(), TG4RunManager::CacheMCStack(), TG4StepManager::CheckGflashSpot(), TG4G3PhysicsManager::CheckLock(), TG4PrimaryGeneratorAction::CheckParticleDefinition(), TG4StepManager::CheckStep(), TG4StepManager::CheckSteppingManager(), TG4StepManager::CheckTrack(), TG4RunManager::ConfigureRunManager(), TG4GeometryManager::ConstructG4GeometryViaVGM(), TG4GeometryManager::ConstructG4GeometryViaVMC(), TG4RunConfiguration::CreatePhysicsList(), TG4StepManager::CurrentVolID(), TG4GeometryManager::FillMediumMapFromG3(), TG4GeometryManager::FillMediumMapFromRoot(), TG4SDConstruction::FillSDSelectionFromTGeo(), TG4EmModelPhysics::GetEmModel(), TG4EmModelPhysics::GetEmModelName(), TG4G3PhysicsManager::GetG3ParticleWSPName(), TG4GeometryServices::GetLimits(), TG4GeometryServices::GetLimits(), TG4GeometryManager::GetMCGeometry(), TG4PhysicsManager::GetOpBoundaryStatus(), TG4ParticlesManager::GetParticle(), TG4ParticlesManager::GetPDGEncoding(), TG4StepManager::GetSecondary(), TG4SDServices::GetSensitiveDetector(), TG4TrackManager::GetTrackInformation(), TG4ParticlesManager::GetUserParticle(), TG4OpGeometryManager::Gfmate(), TG4MCGeometry::Ggclos(), TG4MCGeometry::Gsbool(), TG4MCGeometry::Gsdvn(), TG4MCGeometry::Gsdvn2(), TG4MCGeometry::Gsdvt(), TG4MCGeometry::Gsdvt2(), TG4MCGeometry::Gspos(), TG4MCGeometry::Gsposp(), TG4MCGeometry::Gsvolu(), TG4MCGeometry::Material(), TG4MCGeometry::Matrix(), TG4MCGeometry::Medium(), TG4GeometryServices::MixMaterials(), TG4MCGeometry::Mixture(), TG4MCGeometry::NofVolDaughters(), TG4MCGeometry::NofVolumes(), TG4G3ControlVector::operator[](), TG4G3CutVector::operator[](), TG4StackPopper::PostStepDoIt(), TG4GeometryServices::PrintControls(), TG4GeometryServices::PrintCuts(), TG4StepManager::ProdProcess(), TG4G3CutVector::SetCut(), TG4ParticlesManager::SetDecayMode(), TG4TrackManager::SetParentToTrackInformation(), TG4PhysicsManager::SetSpecialControlsActivation(), TG4PhysicsManager::SetSpecialCutsActivation(), TG4TrackManager::SetTrackInformation(), TG4ParticlesManager::SetUserDecay(), TG4Field::TG4Field(), TG4G3Defaults::TG4G3Defaults(), TG4G3PhysicsManager::TG4G3PhysicsManager(), TG4GeometryManager::TG4GeometryManager(), TG4GeometryServices::TG4GeometryServices(), TG4MCGeometry::TG4MCGeometry(), TG4OpGeometryManager::TG4OpGeometryManager(), TG4ParticlesManager::TG4ParticlesManager(), TG4PhysicsManager::TG4PhysicsManager(), TG4ProcessMap::TG4ProcessMap(), TG4RunConfiguration::TG4RunConfiguration(), TG4RunManager::TG4RunManager(), TG4SDManager::TG4SDManager(), TG4SDServices::TG4SDServices(), TG4SpecialPhysicsList::TG4SpecialPhysicsList(), TG4StackPopper::TG4StackPopper(), TG4StateManager::TG4StateManager(), TG4StepManager::TG4StepManager(), TG4SteppingAction::TG4SteppingAction(), TG4TrackingAction::TG4TrackingAction(), TG4TrackManager::TG4TrackManager(), TG4GeoTrackManager::UpdateRootTrack(), TG4MCGeometry::VolDaughterCopyNo(), TG4MCGeometry::VolDaughterName(), TG4MCGeometry::VolId(), TG4MCGeometry::VolId2Mate(), TG4MCGeometry::VolName(), and TG4PhysicsManager::Xsec().
Warning()
void TG4Globals::Warning (const TString & className, const TString & methodName, const TString & text) static
Print warning message.
Definition at line 48 of file TG4Globals.cxx.
Referenced by TG4MediumMap::AddMedium(), TG4EmModelPhysics::AddModel(), TG4EmModelPhysics::AddModels(), TG4OpGeometryManager::AddUnit(), TG4ComposedPhysicsList::ApplyCrossSectionFactor(), TG4ComposedPhysicsList::ApplyGammaToMuonsCrossSectionFactor(), TG4RunAction::ChangeLooperParameters(), TG4ParticlesChecker::CheckParticle(), TG4PrimaryGeneratorAction::CheckParticleDefinition(), TG4PrimaryGeneratorAction::CheckVMCStack(), Compare(), TG4SpecialPhysicsList::Configure(), TG4RunManager::ConfigureRunManager(), TG4GflashFastSimulation::Construct(), TG4GeometryManager::ConstructLocalFields(), TG4ProcessMapPhysics::ConstructProcess(), TG4UserParticlesPhysics::ConstructProcess(), TG4GeometryServices::ConvertAtomWeight(), TG4TransitionRadiationPhysics::CreateXTRProcess(), TGeant4::DefaultRange(), TG4PhysicsManager::DefineParticle(), TGeant4::DefineParticle(), TG4ParticlesManager::DefineParticles(), TG4RegionsManager::DumpRegion(), TG4GeometryManager::FillMediumMapFromG3(), TG4SDConstruction::FillSDSelectionFromTGeo(), TG4GeometryServices::FindDaughter(), TG4GeometryServices::FindLimits(), TG4GeometryServices::FindLimits2(), TG4GeometryServices::FindLogicalVolume(), TG4GeometryServices::FindPhysicalVolume(), TG4RunManager::FinishRun(), TGeant4::Gckmat(), TGeant4::Gdhead(), TGeant4::Gdman(), TGeant4::Gdopt(), TG4VisManager::Gdraw(), TG4StepManager::Gdtom(), TG4ProcessMap::GetCodes(), TG4StepManager::GetCurrentLimits(), TG4StepManager::GetCurrentOffPhysicalVolume(), TG4CrossSectionManager::GetElement(), TG4VRegionsManager::GetGlobalEnergyCut(), TG4RadiatorDescription::GetLayer(), TG4SDServices::GetLogicalVolume(), TG4MCGeometry::GetMaterial(), TG4OpGeometryManager::GetMaterial(), TG4MediumMap::GetMedia(), TG4MCGeometry::GetMedium(), TG4MediumMap::GetMedium(), TG4MediumMap::GetMedium(), TG4MediumMap::GetMedium(), TG4MediumMap::GetMedium(), TG4ModelConfigurationManager::GetModelConfiguration(), TG4CrossSectionManager::GetParticle(), TG4ParticlesManager::GetParticleDefinition(), TG4PhysicsManager::GetParticleDefinition(), TG4IntMap::GetSecond(), TG4MCGeometry::GetShape(), TG4MCGeometry::GetTransformation(), TG4ParticlesManager::GetUserIon(), TG4SDServices::GetUserSD(), TG4SDServices::GetVolumeID(), TG4SDServices::GetVolumeID(), TG4SDServices::GetVolumeName(), TG4OpGeometryManager::Gfmate(), TG4StepManager::Gmtod(), TG4VisManager::Gsatt(), TG4MCGeometry::Gsord(), TG4PhysicsManager::Gstpar(), TG4PhysicsManager::GstparControl(), TG4PhysicsManager::GstparCut(), TGeant4::InitLego(), TGeant4::InitMT(), TG4StepManager::InterruptTrack(), TG4RegionsManager::LoadRegions(), TG4MediumMap::MapMedium(), TG4MediumMap::MapMedium(), TG4SDServices::MapUserSD(), TG4StepManager::MaxStep(), TG4MCGeometry::MediumId(), TG4PhysicsManager::ParticleMCType(), TG4VRegionsManager::PrintFromG4Table(), TG4RunManager::ProcessEvent(), TG4RunManager::ProcessRun(), TG4VUserFastSimulation::Register(), TG4VRegionsManager::SaveRegions(), TG4OpGeometryManager::SetBorderSurface(), TG4OpGeometryManager::SetCerenkov(), TGeant4::SetClipBox(), TG4G3ControlVector::SetControl(), TG4PhysicsManager::SetCut(), TG4RegionsManager::SetLoad(), TG4ComposedPhysicsList::SetLooperThresholds(), TG4Medium::SetMaterial(), TG4OpGeometryManager::SetMaterialProperty(), TG4OpGeometryManager::SetMaterialProperty(), TG4OpGeometryManager::SetMaterialProperty(), TG4StepManager::SetMaxStepBack(), TG4ModelConfigurationManager::SetModel(), TG4ModelConfigurationManager::SetModelExcludedParticles(), TG4ModelConfigurationManager::SetModelParticles(), TG4ModelConfigurationManager::SetModelRegions(), TG4Medium::SetName(), TG4DetConstructionMessenger::SetNewValue(), TG4ParticlesCheckerMessenger::SetNewValue(), TG4RegionsMessenger::SetNewValue(), TG4ModelConfigurationManager::SetOneModelRegion(), TG4PhysicsManager::SetProcess(), TG4ModelConfigurationManager::SetRegionsNames(), TG4OpGeometryManager::SetSkinSurface(), TG4PhysicsManager::SetSpecialControlsActivation(), TG4PhysicsManager::SetSpecialCutsActivation(), TG4SpecialControlsV2::SetSwitch(), TG4FastSimulationPhysics::SetUserFastSimulation(), TG4StepManager::StopTrack(), TG4GeometryServices::SurfaceFinish(), TG4GeometryServices::SurfaceModel(), TG4GeometryServices::SurfaceType(), TG4FastSimulationPhysics::UpdateRegions(), TG4TrackingAction::UserProcessHits(), TG4SDServices::VolDaughterCopyNo(), TG4SDServices::VolDaughterName(), and TGeant4::WriteEuclid().
Endl()
TString TG4Globals::Endl () inline static
Special endl which is then reformatted in Warning and Exception
Definition at line 101 of file TG4Globals.h.
Referenced by TG4ParticlesManager::AddIon(), TG4ActionInitialization::Build(), TG4G3PhysicsManager::CheckLock(), TG4GeometryManager::ConstructG4GeometryViaVGM(), TG4GeometryManager::ConstructG4GeometryViaVMC(), TG4RunConfiguration::CreatePhysicsList(), TG4TransitionRadiationPhysics::CreateXTRProcess(), TG4PhysicsManager::DefineParticle(), TG4GeometryManager::FillMediumMapFromG3(), TG4VRegionsManager::GetGlobalEnergyCut(), TG4SDServices::MapUserSD(), TG4VRegionsManager::PrintFromG4Table(), TG4VUserFastSimulation::Register(), TG4OpGeometryManager::SetBorderSurface(), TG4ModelConfigurationManager::SetModelExcludedParticles(), TG4ModelConfigurationManager::SetModelParticles(), TG4ModelConfigurationManager::SetModelRegions(), TG4DetConstructionMessenger::SetNewValue(), TG4ModelConfigurationManager::SetOneModelRegion(), TG4ModelConfigurationManager::SetRegionsNames(), and TG4RunConfiguration::TG4RunConfiguration().
AppendNumberToString()
void TG4Globals::AppendNumberToString (G4String & string, G4int number) static
Append number to string.
Definition at line 63 of file TG4Globals.cxx.
Referenced by TG4StepManager::CurrentVolPath().
Compare()
G4bool TG4Globals::Compare (G4bool activation, TG4G3ControlValue controlValue) static
Compare the boolean value of the process activation with the process control value. Return true if the values correspond, false otherwise.
Definition at line 81 of file TG4Globals.cxx.
Referenced by TG4SpecialControlsV2::ApplyControls(), and TG4PhysicsManager::SetSpecialControlsActivation().
PrintStars()
void TG4Globals::PrintStars (G4bool emptyLineFirst) static
Print stars.
Definition at line 99 of file TG4Globals.cxx.
Referenced by TG4GeometryServices::PrintStatistics(), and TG4SDServices::PrintStatistics().
Help()
G4String TG4Globals::Help () static
Return VMC mailing list address.
Definition at line 111 of file TG4Globals.cxx.
GetToken()
G4String TG4Globals::GetToken (Int_t i, const TString & s) static
Tokenize the given string and return the i-th token
Definition at line 119 of file TG4Globals.cxx.
Referenced by TG4SpecialPhysicsList::Configure(), TG4RunConfiguration::CreatePhysicsList(), TG4SpecialPhysicsList::IsAvailableSelection(), and TG4RunConfiguration::TG4RunConfiguration().
Contains()
G4bool TG4Globals::Contains (const G4String & name, const G4String & nameList) static
Append a space to both searched name and the list in order to exclude a match for names which are only substrings of some name present in the list. Eg. when omega_c0 is in the list and omega is checked for a presence
Definition at line 153 of file TG4Globals.cxx.
Referenced by TG4ExtDecayerPhysics::ConstructProcess(), TG4StackPopperPhysics::ConstructProcess(), and TG4ModelConfiguration::HasParticle().
Member Data Documentation
fgkEndl
const TString TG4Globals::fgkEndl = "x\n" static private
Special endl.
Definition at line 95 of file TG4Globals.h.
Referenced by Endl().
fgkTokenSeparator
const char TG4Globals::fgkTokenSeparator = '+' static private
Separator in GetToken() method.
Definition at line 96 of file TG4Globals.h.
Referenced by GetToken().
The documentation for this class was generated from the following files:
source/global/include/TG4Globals.h
source/global/src/TG4Globals.cxx