Geant4 VMC: TG4G3Defaults Class Reference
TG4G3Defaults Class Reference
global
Default G3 kinetic energy cuts and control process values.
#include <TG4G3Defaults.h>
Public Member Functions
TG4G3Defaults ()
~TG4G3Defaults ()
G4bool IsDefaultCut (TG4G3Cut cut, G4double value) const
G4bool IsDefaultControl (TG4G3Control control, TG4G3ControlValue value) const
G4double CutValue (G4int cut) const
TG4G3ControlValue ControlValue (G4int control) const
Static Public Member Functions
static TG4G3Defaults * Instance ()
Private Member Functions
TG4G3Defaults (const TG4G3Defaults &right)
Not implemented.
TG4G3Defaults & operator= (const TG4G3Defaults &right)
Not implemented.
Private Attributes
TG4G3CutVector fCutVector
vector of default cut values
TG4G3ControlVector fControlVector
vector of default control values
Static Private Attributes
static TG4G3Defaults * fgInstance = 0
this instance
Detailed Description
Default G3 kinetic energy cuts and control process values.
Class provides the default G3 values of the kinetic energy cuts for particles and the control process parameters.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 33 of file TG4G3Defaults.h.
Constructor & Destructor Documentation
TG4G3Defaults() [1/2]
TG4G3Defaults::TG4G3Defaults ()
Default constructor
Definition at line 27 of file TG4G3Defaults.cxx.
Referenced by Instance(), operator=(), and TG4G3Defaults().
~TG4G3Defaults()
TG4G3Defaults::~TG4G3Defaults ()
Destructor
Definition at line 71 of file TG4G3Defaults.cxx.
TG4G3Defaults() [2/2]
TG4G3Defaults::TG4G3Defaults (const TG4G3Defaults & right) private
Not implemented.
Member Function Documentation
Instance()
TG4G3Defaults * TG4G3Defaults::Instance () inline static
Return this instance
Definition at line 66 of file TG4G3Defaults.h.
Referenced by TG4VRegionsManager::GetGlobalEnergyCut(), TG4G3ControlVector::SetG3Defaults(), and TG4G3CutVector::SetG3Defaults().
IsDefaultCut()
G4bool TG4G3Defaults::IsDefaultCut (TG4G3Cut cut, G4double value) const
Test if the parameter value is equal to the G3 default value.
Definition at line 99 of file TG4G3Defaults.cxx.
IsDefaultControl()
G4bool TG4G3Defaults::IsDefaultControl (TG4G3Control control, TG4G3ControlValue value) const
Test if the parameter value is equal to the G3 default value.
Definition at line 110 of file TG4G3Defaults.cxx.
CutValue()
G4double TG4G3Defaults::CutValue (G4int cut) const
Return the G3 default value for the specified cut.
Definition at line 83 of file TG4G3Defaults.cxx.
Referenced by TG4VRegionsManager::GetGlobalEnergyCut(), IsDefaultCut(), and TG4G3CutVector::SetG3Defaults().
ControlValue()
TG4G3ControlValue TG4G3Defaults::ControlValue (G4int control) const
Return the G3 default value for the specified control.
Definition at line 91 of file TG4G3Defaults.cxx.
Referenced by IsDefaultControl().
operator=()
TG4G3Defaults & TG4G3Defaults::operator= (const TG4G3Defaults & right) private
Not implemented.
Member Data Documentation
fgInstance
TG4G3Defaults * TG4G3Defaults::fgInstance = 0 static private
this instance
Definition at line 57 of file TG4G3Defaults.h.
Referenced by Instance(), TG4G3Defaults(), and ~TG4G3Defaults().
fCutVector
TG4G3CutVector TG4G3Defaults::fCutVector private
vector of default cut values
Definition at line 60 of file TG4G3Defaults.h.
Referenced by CutValue(), and TG4G3Defaults().
fControlVector
TG4G3ControlVector TG4G3Defaults::fControlVector private
vector of default control values
Definition at line 61 of file TG4G3Defaults.h.
Referenced by ControlValue(), and TG4G3Defaults().
The documentation for this class was generated from the following files:
source/global/include/TG4G3Defaults.h
source/global/src/TG4G3Defaults.cxx