Geant4 VMC: TG4ProcessMap Class Reference
TG4ProcessMap Class Reference
global
Maps G4 process sub types to TMCProcess and TG4G3Control codes.
#include <TG4ProcessMap.h>
Public Member Functions
TG4ProcessMap ()
TG4ProcessMap (const TG4ProcessMap &right)=delete
TG4ProcessMap & operator= (const TG4ProcessMap &right)=delete
~TG4ProcessMap ()
G4bool Add (G4int subType, TMCProcess mcProcess, TG4G3Control g3Control)
void PrintAll () const
void Clear ()
std::pair< TMCProcess, TG4G3Control > GetCodes (const G4VProcess *process) const
TMCProcess GetMCProcess (const G4VProcess *process) const
TG4G3Control GetControl (const G4VProcess *process) const
G4String GetMCProcessName (const G4VProcess *process) const
G4String GetControlName (const G4VProcess *process) const
Static Public Member Functions
static TG4ProcessMap * Instance ()
Private Member Functions
G4bool IsDefined (G4int subType)
Private Attributes
std::map< G4int, std::pair< TMCProcess, TG4G3Control > > fMap
map container
Static Private Attributes
static TG4ProcessMap * fgInstance = 0
this instance
Detailed Description
Maps G4 process sub types to TMCProcess and TG4G3Control codes.
Singleton map container for associated pairs of G4 process sub types and TMCProcess and TG4G3Control code.
Author
I. Hrivnacova; IJClab Orsay
Definition at line 36 of file TG4ProcessMap.h.
Constructor & Destructor Documentation
TG4ProcessMap() [1/2]
TG4ProcessMap::TG4ProcessMap ()
Default constructor
Definition at line 26 of file TG4ProcessMap.cxx.
Referenced by Instance(), operator=(), and TG4ProcessMap().
TG4ProcessMap() [2/2]
TG4ProcessMap::TG4ProcessMap (const TG4ProcessMap & right) delete
~TG4ProcessMap()
TG4ProcessMap::~TG4ProcessMap ()
Destructor
Definition at line 39 of file TG4ProcessMap.cxx.
Member Function Documentation
operator=()
TG4ProcessMap & TG4ProcessMap::operator= (const TG4ProcessMap & right) delete
Instance()
TG4ProcessMap * TG4ProcessMap::Instance () inline static
Return this instance
Definition at line 72 of file TG4ProcessMap.h.
Referenced by TG4ProcessMapPhysics::ConstructProcess(), TG4ProcessMapPhysics::FillMap(), TG4G3ControlVector::GetControlValue(), and TG4ComposedPhysicsMessenger::SetNewValue().
Add()
G4bool TG4ProcessMap::Add (G4int subType, TMCProcess mcProcess, TG4G3Control g3Control)
Add the pair to the map.
Definition at line 66 of file TG4ProcessMap.cxx.
Referenced by TG4ProcessMapPhysics::FillMap().
PrintAll()
void TG4ProcessMap::PrintAll () const
Dump the whole map.
Definition at line 81 of file TG4ProcessMap.cxx.
Referenced by TG4ComposedPhysicsMessenger::SetNewValue().
Clear()
void TG4ProcessMap::Clear ()
Clear the map.
Definition at line 99 of file TG4ProcessMap.cxx.
GetCodes()
std::pair< TMCProcess, TG4G3Control > TG4ProcessMap::GetCodes (const G4VProcess * process) const
Return the pair of TMCProcess and G3 control codes for the process with a given name.
Definition at line 108 of file TG4ProcessMap.cxx.
Referenced by GetControl(), and GetMCProcess().
GetMCProcess()
TMCProcess TG4ProcessMap::GetMCProcess (const G4VProcess * process) const
Return TMCProcess code for the process with a given name.
Definition at line 129 of file TG4ProcessMap.cxx.
Referenced by GetMCProcessName().
GetControl()
TG4G3Control TG4ProcessMap::GetControl (const G4VProcess * process) const
Return G3 control code for the process with a given name.
Definition at line 137 of file TG4ProcessMap.cxx.
Referenced by GetControlName(), and TG4G3ControlVector::GetControlValue().
GetMCProcessName()
G4String TG4ProcessMap::GetMCProcessName (const G4VProcess * process) const
Return TMCProcess code for the process with a given name.
Definition at line 145 of file TG4ProcessMap.cxx.
GetControlName()
G4String TG4ProcessMap::GetControlName (const G4VProcess * process) const
Return G3 control code for the process with a given name.
Definition at line 155 of file TG4ProcessMap.cxx.
IsDefined()
G4bool TG4ProcessMap::IsDefined (G4int subType) private
Return true if the first is already in the map.
Definition at line 51 of file TG4ProcessMap.cxx.
Referenced by Add().
Member Data Documentation
fgInstance
TG4ProcessMap * TG4ProcessMap::fgInstance = 0 static private
this instance
Definition at line 64 of file TG4ProcessMap.h.
Referenced by Instance(), TG4ProcessMap(), and ~TG4ProcessMap().
fMap
std::map<G4int, std::pair<TMCProcess, TG4G3Control> > TG4ProcessMap::fMap private
map container
Definition at line 67 of file TG4ProcessMap.h.
Referenced by Add(), Clear(), GetCodes(), IsDefined(), PrintAll(), and TG4ProcessMap().
The documentation for this class was generated from the following files:
source/global/include/TG4ProcessMap.h
source/global/src/TG4ProcessMap.cxx