Geant4 VMC: TG4ComposedPhysicsList Class Reference
TG4ComposedPhysicsList Class Reference
physics_list
The Geant4 VMC physics list builder.
#include <TG4ComposedPhysicsList.h>
Public Member Functions
TG4ComposedPhysicsList ()
virtual ~TG4ComposedPhysicsList ()
void AddPhysicsList (G4VUserPhysicsList *physicsList)
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
void SetCutForGamma (G4double cut)
void SetCutForElectron (G4double cut)
void SetCutForPositron (G4double cut)
void SetCutForProton (G4double cut)
void SetProductionCutsTableEnergyRange (G4double min, G4double max)
void SetGammaToMuonsCrossSectionFactor (G4double value)
void SetCrossSectionFactor (const G4String &particleName, const G4String &processDef, G4double value, G4bool isProcessName)
void SetLooperThresholdsLevel (G4int level)
void PrintAllProcesses () const
void DumpAllProcesses () const
virtual G4int VerboseLevel () const
virtual void VerboseLevel (G4int level)
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
Private Member Functions
TG4ComposedPhysicsList (const TG4ComposedPhysicsList &right)
Not implemented.
TG4ComposedPhysicsList & operator= (const TG4ComposedPhysicsList &right)
Not implemented.
void ApplyGammaToMuonsCrossSectionFactor ()
void ApplyCrossSectionFactor (const G4String &particleName, const G4String &processDef, G4double value, G4bool isProcessName)
void ApplyCrossSectionFactors ()
void SetLooperThresholds ()
Private Attributes
TG4ComposedPhysicsMessenger fMessenger
messenger
std::vector< G4VUserPhysicsList * > fPhysicsLists
physics lists
G4bool fIsProductionCutsTableEnergyRange
Info if the production cuts table energy range is redefined by user.
G4double fProductionCutsTableEnergyMin
The production cuts table energy range minimum redefined by user.
G4double fProductionCutsTableEnergyMax
The production cuts table energy range maximum redefined by user.
G4double fGammaToMuonsCrossSectionFactor
Gamma to muons cross section factor.
std::vector< std::tuple< G4String, G4String, G4double, G4bool > > fCrossSectionFactors
Cross section factors by process type or name.
G4int fLooperThresholdsLevel
Looper threshold level (can have valuee 0,1,2)
Static Private Attributes
static const G4double fgkDefautLooperThresholdsLevel = 1
the default cut value
Detailed Description
The Geant4 VMC physics list builder.
The helper class which allows to combine more physics list together.
Author
I. Hrivnacova; IPN Orsay
Definition at line 36 of file TG4ComposedPhysicsList.h.
Constructor & Destructor Documentation
TG4ComposedPhysicsList() [1/2]
TG4ComposedPhysicsList::TG4ComposedPhysicsList ()
Default constructor
Definition at line 152 of file TG4ComposedPhysicsList.cxx.
Referenced by operator=(), and TG4ComposedPhysicsList().
~TG4ComposedPhysicsList()
TG4ComposedPhysicsList::~TG4ComposedPhysicsList () virtual
Destructor
Definition at line 172 of file TG4ComposedPhysicsList.cxx.
TG4ComposedPhysicsList() [2/2]
TG4ComposedPhysicsList::TG4ComposedPhysicsList (const TG4ComposedPhysicsList & right) private
Not implemented.
Member Function Documentation
AddPhysicsList()
void TG4ComposedPhysicsList::AddPhysicsList (G4VUserPhysicsList * physicsList)
Add physics list in the list
Definition at line 327 of file TG4ComposedPhysicsList.cxx.
Referenced by TG4RunConfiguration::CreatePhysicsList().
ConstructParticle()
void TG4ComposedPhysicsList::ConstructParticle () virtual
Construct all particles.
Definition at line 335 of file TG4ComposedPhysicsList.cxx.
Referenced by ConstructParticle().
ConstructProcess()
void TG4ComposedPhysicsList::ConstructProcess () virtual
Construct all processes.
Definition at line 350 of file TG4ComposedPhysicsList.cxx.
SetCuts()
void TG4ComposedPhysicsList::SetCuts () virtual
Set cut values
Definition at line 389 of file TG4ComposedPhysicsList.cxx.
SetCutForGamma()
void TG4ComposedPhysicsList::SetCutForGamma (G4double cut)
Set cut value for gamma
Definition at line 438 of file TG4ComposedPhysicsList.cxx.
SetCutForElectron()
void TG4ComposedPhysicsList::SetCutForElectron (G4double cut)
Set cut value for electron
Definition at line 446 of file TG4ComposedPhysicsList.cxx.
SetCutForPositron()
void TG4ComposedPhysicsList::SetCutForPositron (G4double cut)
Set cut value for positron
Definition at line 454 of file TG4ComposedPhysicsList.cxx.
SetCutForProton()
void TG4ComposedPhysicsList::SetCutForProton (G4double cut)
Set cut value for positron
Definition at line 462 of file TG4ComposedPhysicsList.cxx.
SetProductionCutsTableEnergyRange()
void TG4ComposedPhysicsList::SetProductionCutsTableEnergyRange (G4double min, G4double max)
Set the production cuts table energy range
Definition at line 470 of file TG4ComposedPhysicsList.cxx.
SetGammaToMuonsCrossSectionFactor()
void TG4ComposedPhysicsList::SetGammaToMuonsCrossSectionFactor (G4double value) inline
Set gamma to muons cross section factor
Definition at line 112 of file TG4ComposedPhysicsList.h.
SetCrossSectionFactor()
void TG4ComposedPhysicsList::SetCrossSectionFactor (const G4String & particleName, const G4String & processDef, G4double value, G4bool isProcessName)
Define a scale factor for a hadronic process defined by its name or its type name (depending on the 'isProcessName' setting) for the particle with the given name.
Definition at line 481 of file TG4ComposedPhysicsList.cxx.
SetLooperThresholdsLevel()
void TG4ComposedPhysicsList::SetLooperThresholdsLevel (G4int level) inline
Set gamma to muons cross section factor
Definition at line 119 of file TG4ComposedPhysicsList.h.
PrintAllProcesses()
void TG4ComposedPhysicsList::PrintAllProcesses () const
Print all processes.
Definition at line 494 of file TG4ComposedPhysicsList.cxx.
DumpAllProcesses()
void TG4ComposedPhysicsList::DumpAllProcesses () const
Dump all particles and their processes.
Definition at line 511 of file TG4ComposedPhysicsList.cxx.
VerboseLevel() [1/2]
G4int TG4ComposedPhysicsList::VerboseLevel () const virtual
Return verbose level (via TG4Verbose)
Reimplemented from TG4Verbose.
Definition at line 536 of file TG4ComposedPhysicsList.cxx.
Referenced by ApplyCrossSectionFactor(), ApplyGammaToMuonsCrossSectionFactor(), ConstructParticle(), ConstructProcess(), SetCuts(), SetLooperThresholds(), and TG4ComposedPhysicsList().
VerboseLevel() [2/2]
void TG4ComposedPhysicsList::VerboseLevel (G4int level) virtual
Set the specified level to both TG4Verbose and G4VUserPhysicsList. The verbose level is also propagated to registered physics lists.
Reimplemented from TG4Verbose.
Definition at line 544 of file TG4ComposedPhysicsList.cxx.
operator=()
TG4ComposedPhysicsList & TG4ComposedPhysicsList::operator= (const TG4ComposedPhysicsList & right) private
Not implemented.
ApplyGammaToMuonsCrossSectionFactor()
void TG4ComposedPhysicsList::ApplyGammaToMuonsCrossSectionFactor () private
Apply gamma to muons cross section factor if defined by user if applicaple
Definition at line 185 of file TG4ComposedPhysicsList.cxx.
Referenced by ConstructProcess().
ApplyCrossSectionFactor()
void TG4ComposedPhysicsList::ApplyCrossSectionFactor (const G4String & particleName, const G4String & processDef, G4double value, G4bool isProcessName) private
Apply the scale factor to a hadronic process cross section
Definition at line 219 of file TG4ComposedPhysicsList.cxx.
Referenced by ApplyCrossSectionFactors().
ApplyCrossSectionFactors()
void TG4ComposedPhysicsList::ApplyCrossSectionFactors () private
Apply the cross section factors registered in fCrossSectionFactors
Definition at line 283 of file TG4ComposedPhysicsList.cxx.
Referenced by ConstructProcess().
SetLooperThresholds()
void TG4ComposedPhysicsList::SetLooperThresholds () private
Apply the looper thresholds level
Definition at line 294 of file TG4ComposedPhysicsList.cxx.
Referenced by ConstructProcess().
Member Data Documentation
fgkDefautLooperThresholdsLevel
const G4double TG4ComposedPhysicsList::fgkDefautLooperThresholdsLevel = 1 static private
the default cut value
Definition at line 85 of file TG4ComposedPhysicsList.h.
Referenced by ConstructProcess(), and TG4ComposedPhysicsList().
fMessenger
TG4ComposedPhysicsMessenger TG4ComposedPhysicsList::fMessenger private
messenger
Definition at line 88 of file TG4ComposedPhysicsList.h.
Referenced by TG4ComposedPhysicsList().
fPhysicsLists
std::vector<G4VUserPhysicsList*> TG4ComposedPhysicsList::fPhysicsLists private
physics lists
Definition at line 89 of file TG4ComposedPhysicsList.h.
Referenced by AddPhysicsList(), ConstructParticle(), ConstructProcess(), TG4ComposedPhysicsList(), VerboseLevel(), and ~TG4ComposedPhysicsList().
fIsProductionCutsTableEnergyRange
G4bool TG4ComposedPhysicsList::fIsProductionCutsTableEnergyRange private
Info if the production cuts table energy range is redefined by user.
Definition at line 92 of file TG4ComposedPhysicsList.h.
Referenced by SetCuts(), SetProductionCutsTableEnergyRange(), and TG4ComposedPhysicsList().
fProductionCutsTableEnergyMin
G4double TG4ComposedPhysicsList::fProductionCutsTableEnergyMin private
The production cuts table energy range minimum redefined by user.
Definition at line 95 of file TG4ComposedPhysicsList.h.
Referenced by SetCuts(), SetProductionCutsTableEnergyRange(), and TG4ComposedPhysicsList().
fProductionCutsTableEnergyMax
G4double TG4ComposedPhysicsList::fProductionCutsTableEnergyMax private
The production cuts table energy range maximum redefined by user.
Definition at line 98 of file TG4ComposedPhysicsList.h.
Referenced by SetCuts(), SetProductionCutsTableEnergyRange(), and TG4ComposedPhysicsList().
fGammaToMuonsCrossSectionFactor
G4double TG4ComposedPhysicsList::fGammaToMuonsCrossSectionFactor private
Gamma to muons cross section factor.
Definition at line 101 of file TG4ComposedPhysicsList.h.
Referenced by ApplyGammaToMuonsCrossSectionFactor(), ConstructProcess(), SetGammaToMuonsCrossSectionFactor(), and TG4ComposedPhysicsList().
fCrossSectionFactors
std::vector<std::tuple<G4String, G4String, G4double, G4bool> > TG4ComposedPhysicsList::fCrossSectionFactors private
Cross section factors by process type or name.
Definition at line 104 of file TG4ComposedPhysicsList.h.
Referenced by ApplyCrossSectionFactors(), ConstructProcess(), and SetCrossSectionFactor().
fLooperThresholdsLevel
G4int TG4ComposedPhysicsList::fLooperThresholdsLevel private
Looper threshold level (can have valuee 0,1,2)
Definition at line 107 of file TG4ComposedPhysicsList.h.
Referenced by ConstructProcess(), SetLooperThresholds(), SetLooperThresholdsLevel(), and TG4ComposedPhysicsList().
The documentation for this class was generated from the following files:
source/physics_list/include/TG4ComposedPhysicsList.h
source/physics_list/src/TG4ComposedPhysicsList.cxx