Geant4 VMC: TG4HadronPhysicsList Class Reference
TG4HadronPhysicsList Class Reference
physics_list
The hadron physics list helper class.
#include <TG4HadronPhysicsList.h>
Public Member Functions
TG4HadronPhysicsList (const G4String &selection)
virtual ~TG4HadronPhysicsList ()
virtual void ConstructParticle ()
virtual void ConstructProcess ()
virtual void SetCuts ()
No cuts are set here.
virtual G4int VerboseLevel () const
virtual void VerboseLevel (G4int level)
void SetRangeCut (G4double value)
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
Static Public Member Functions
static G4String AvailableHadronSelections ()
static G4String AvailableEMSelections ()
static G4bool IsAvailableSelection (const G4String &selection)
Static Protected Attributes
static const G4double fgkDefaultCutValue = 1.0 * mm
default cut value
Private Member Functions
TG4HadronPhysicsList (const TG4HadronPhysicsList &right)
Not implemented.
TG4HadronPhysicsList & operator= (const TG4HadronPhysicsList &right)
Not implemented.
void Configure (const G4String &selection)
Private Attributes
G4VUserPhysicsList * fPhysicsList
the physics list according to user selection
Detailed Description
The hadron physics list helper class.
The hadron physics list instatiates the Geant4 hadron physics list selected by its name in the constructor
Author
I. Hrivnacova; IPN Orsay
Definition at line 31 of file TG4HadronPhysicsList.h.
Constructor & Destructor Documentation
TG4HadronPhysicsList() [1/2]
TG4HadronPhysicsList::TG4HadronPhysicsList (const G4String & selection)
Standard constructor
Definition at line 78 of file TG4HadronPhysicsList.cxx.
Referenced by operator=(), and TG4HadronPhysicsList().
~TG4HadronPhysicsList()
TG4HadronPhysicsList::~TG4HadronPhysicsList () virtual
Destructor
Definition at line 91 of file TG4HadronPhysicsList.cxx.
TG4HadronPhysicsList() [2/2]
TG4HadronPhysicsList::TG4HadronPhysicsList (const TG4HadronPhysicsList & right) private
Not implemented.
Member Function Documentation
AvailableHadronSelections()
G4String TG4HadronPhysicsList::AvailableHadronSelections () static
Return list of all available hadron physics lists selections
Definition at line 28 of file TG4HadronPhysicsList.cxx.
Referenced by TG4RunConfiguration::TG4RunConfiguration().
AvailableEMSelections()
G4String TG4HadronPhysicsList::AvailableEMSelections () static
Return list of all available EM options selections
Definition at line 47 of file TG4HadronPhysicsList.cxx.
Referenced by TG4RunConfiguration::TG4RunConfiguration().
IsAvailableSelection()
G4bool TG4HadronPhysicsList::IsAvailableSelection (const G4String & selection) static
Return list of all available selections
Definition at line 65 of file TG4HadronPhysicsList.cxx.
Referenced by TG4RunConfiguration::CreatePhysicsList(), and TG4RunConfiguration::TG4RunConfiguration().
ConstructParticle()
void TG4HadronPhysicsList::ConstructParticle () virtual
Construct particles.
Definition at line 119 of file TG4HadronPhysicsList.cxx.
ConstructProcess()
void TG4HadronPhysicsList::ConstructProcess () virtual
Construct processes.
Definition at line 128 of file TG4HadronPhysicsList.cxx.
SetCuts()
virtual void TG4HadronPhysicsList::SetCuts () inline virtual
No cuts are set here.
Definition at line 47 of file TG4HadronPhysicsList.h.
VerboseLevel() [1/2]
G4int TG4HadronPhysicsList::VerboseLevel () const virtual
Return verbose level (via TG4Verbose)
Reimplemented from TG4Verbose.
Definition at line 140 of file TG4HadronPhysicsList.cxx.
Referenced by ConstructProcess().
VerboseLevel() [2/2]
void TG4HadronPhysicsList::VerboseLevel (G4int level) virtual
Set the specified level to both TG4Verbose and G4VModularPhysicsList. The verbose level is also propagated to the registered physics list.
Reimplemented from TG4Verbose.
Definition at line 148 of file TG4HadronPhysicsList.cxx.
SetRangeCut()
void TG4HadronPhysicsList::SetRangeCut (G4double value)
Reset the default cut to a given value.
!!! Should be used only in PreInit phase, use SetDefaultCutValue() method of base class to reset the cut value in later phases.
Definition at line 159 of file TG4HadronPhysicsList.cxx.
operator=()
TG4HadronPhysicsList & TG4HadronPhysicsList::operator= (const TG4HadronPhysicsList & right) private
Not implemented.
Configure()
void TG4HadronPhysicsList::Configure (const G4String & selection) private
Create the selected physics constructors and registeres them in the modular physics list.
Definition at line 104 of file TG4HadronPhysicsList.cxx.
Referenced by TG4HadronPhysicsList().
Member Data Documentation
fgkDefaultCutValue
const G4double TG4HadronPhysicsList::fgkDefaultCutValue = 1.0 * mm static protected
default cut value
Definition at line 57 of file TG4HadronPhysicsList.h.
Referenced by TG4HadronPhysicsList().
fPhysicsList
G4VUserPhysicsList* TG4HadronPhysicsList::fPhysicsList private
the physics list according to user selection
Definition at line 71 of file TG4HadronPhysicsList.h.
Referenced by Configure(), ConstructParticle(), ConstructProcess(), and VerboseLevel().
The documentation for this class was generated from the following files:
source/physics_list/include/TG4HadronPhysicsList.h
source/physics_list/src/TG4HadronPhysicsList.cxx