Geant4 VMC: TG4StateManager Class Reference
TG4StateManager Class Reference
geometry
The manager class for application state.
#include <TG4StateManager.h>
Public Member Functions
TG4StateManager ()
virtual ~TG4StateManager ()
void SetNewState (TG4ApplicationState state)
TG4ApplicationState GetCurrentState () const
TG4ApplicationState GetPreviousState () const
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Static Public Member Functions
static TG4StateManager * Instance ()
static G4String GetStateName (TG4ApplicationState state)
Private Member Functions
TG4StateManager (const TG4StateManager &right)
Not implemented.
TG4StateManager & operator= (const TG4StateManager &right)
Not implemented.
Private Attributes
TG4ApplicationState fCurrentState
the current application state
TG4ApplicationState fPreviousState
the previous application state
Static Private Attributes
static G4ThreadLocal TG4StateManager * fgInstance = 0
this instance
Detailed Description
The manager class for application state.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 30 of file TG4StateManager.h.
Constructor & Destructor Documentation
TG4StateManager() [1/2]
TG4StateManager::TG4StateManager ()
Standard constructor
Definition at line 49 of file TG4StateManager.cxx.
Referenced by Instance(), operator=(), and TG4StateManager().
~TG4StateManager()
TG4StateManager::~TG4StateManager () virtual
Destructor
Definition at line 66 of file TG4StateManager.cxx.
TG4StateManager() [2/2]
TG4StateManager::TG4StateManager (const TG4StateManager & right) private
Not implemented.
Member Function Documentation
Instance()
TG4StateManager * TG4StateManager::Instance () inline static
Return this instance
Definition at line 61 of file TG4StateManager.h.
Referenced by TG4RunManager::ConfigureRunManager(), TG4SDConstruction::Construct(), TG4GeometryManager::ConstructG4Geometry(), TG4GeometryManager::ConstructGeometry(), TG4UserParticlesPhysics::ConstructParticle(), TG4PhysicsManager::DefineParticles(), TG4PrimaryGeneratorAction::GeneratePrimaries(), and TG4EventAction::LateInitialize().
GetStateName()
G4String TG4StateManager::GetStateName (TG4ApplicationState state) static
Return string for given application state
Definition at line 21 of file TG4StateManager.cxx.
Referenced by SetNewState().
SetNewState()
void TG4StateManager::SetNewState (TG4ApplicationState state)
Set application state
Definition at line 74 of file TG4StateManager.cxx.
Referenced by TG4RunManager::ConfigureRunManager(), TG4SDConstruction::Construct(), TG4GeometryManager::ConstructG4Geometry(), TG4GeometryManager::ConstructGeometry(), TG4UserParticlesPhysics::ConstructParticle(), TG4PhysicsManager::DefineParticles(), and TG4PrimaryGeneratorAction::GeneratePrimaries().
GetCurrentState()
TG4ApplicationState TG4StateManager::GetCurrentState () const inline
Return application state
Definition at line 67 of file TG4StateManager.h.
GetPreviousState()
TG4ApplicationState TG4StateManager::GetPreviousState () const inline
Return application state
Definition at line 73 of file TG4StateManager.h.
operator=()
TG4StateManager & TG4StateManager::operator= (const TG4StateManager & right) private
Not implemented.
Member Data Documentation
fgInstance
G4ThreadLocal TG4StateManager * TG4StateManager::fgInstance = 0 static private
this instance
Definition at line 52 of file TG4StateManager.h.
Referenced by Instance(), TG4StateManager(), and ~TG4StateManager().
fCurrentState
TG4ApplicationState TG4StateManager::fCurrentState private
the current application state
Definition at line 55 of file TG4StateManager.h.
Referenced by GetCurrentState(), SetNewState(), and TG4StateManager().
fPreviousState
TG4ApplicationState TG4StateManager::fPreviousState private
the previous application state
Definition at line 56 of file TG4StateManager.h.
Referenced by GetPreviousState(), SetNewState(), and TG4StateManager().
The documentation for this class was generated from the following files:
source/global/include/TG4StateManager.h
source/global/src/TG4StateManager.cxx