Geant4 VMC: TG4VUserFastSimulation Class Reference
TG4VUserFastSimulation Class Reference abstract
physics_list
The abstract base class which is used to build fast simulation models.
#include <TG4VUserFastSimulation.h>
Public Member Functions
TG4VUserFastSimulation ()
virtual ~TG4VUserFastSimulation ()
virtual void Construct ()=0
Method to be overriden by user.
Protected Member Functions
void SetModel (const G4String &modelName)
Method to be utilized to register each fast simulation model by name.
void SetModelParticles (const G4String &modelName, const G4String &particles)
Method to be utilized to apply fast simulation model to selected particles.
void SetModelRegions (const G4String &modelName, const G4String &regions)
Method to be utilized to apply fast simulation model to selected regions.
void Register (G4VFastSimulationModel *fastSimulationModel)
Method to be utilized to register each fast simulation model.
Private Member Functions
TG4VUserFastSimulation (const TG4VUserFastSimulation &right)
Not implemented.
TG4VUserFastSimulation & operator= (const TG4VUserFastSimulation &right)
Not implemented.
Private Attributes
TG4ModelConfigurationManager * fFastModelsManager
the fast simulation models manager
Detailed Description
The abstract base class which is used to build fast simulation models.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 31 of file TG4VUserFastSimulation.h.
Constructor & Destructor Documentation
TG4VUserFastSimulation() [1/2]
TG4VUserFastSimulation::TG4VUserFastSimulation ()
Default constructor
Definition at line 24 of file TG4VUserFastSimulation.cxx.
Referenced by operator=(), TG4GflashFastSimulation::TG4GflashFastSimulation(), and TG4VUserFastSimulation().
~TG4VUserFastSimulation()
TG4VUserFastSimulation::~TG4VUserFastSimulation () virtual
Destructor
Definition at line 34 of file TG4VUserFastSimulation.cxx.
TG4VUserFastSimulation() [2/2]
TG4VUserFastSimulation::TG4VUserFastSimulation (const TG4VUserFastSimulation & right) private
Not implemented.
Member Function Documentation
Construct()
virtual void TG4VUserFastSimulation::Construct () pure virtual
Method to be overriden by user.
Implemented in TG4GflashFastSimulation.
SetModel()
void TG4VUserFastSimulation::SetModel (const G4String & modelName) protected
Method to be utilized to register each fast simulation model by name.
Definition at line 44 of file TG4VUserFastSimulation.cxx.
SetModelParticles()
void TG4VUserFastSimulation::SetModelParticles (const G4String & modelName, const G4String & particles) protected
Method to be utilized to apply fast simulation model to selected particles.
Definition at line 50 of file TG4VUserFastSimulation.cxx.
SetModelRegions()
void TG4VUserFastSimulation::SetModelRegions (const G4String & modelName, const G4String & regions) protected
Method to be utilized to apply fast simulation model to selected regions.
Definition at line 57 of file TG4VUserFastSimulation.cxx.
Register()
void TG4VUserFastSimulation::Register (G4VFastSimulationModel * fastSimulationModel) protected
Method to be utilized to register each fast simulation model.
Register the user fast simulation model
Definition at line 64 of file TG4VUserFastSimulation.cxx.
Referenced by TG4GflashFastSimulation::Construct().
operator=()
TG4VUserFastSimulation & TG4VUserFastSimulation::operator= (const TG4VUserFastSimulation & right) private
Not implemented.
Member Data Documentation
fFastModelsManager
TG4ModelConfigurationManager* TG4VUserFastSimulation::fFastModelsManager private
the fast simulation models manager
Definition at line 61 of file TG4VUserFastSimulation.h.
Referenced by Register(), SetModel(), SetModelParticles(), SetModelRegions(), and TG4VUserFastSimulation().
The documentation for this class was generated from the following files:
source/physics_list/include/TG4VUserFastSimulation.h
source/physics_list/src/TG4VUserFastSimulation.cxx