Geant4 VMC: TG4Verbose Class Reference
TG4Verbose Class Reference
global
Base class for defining the verbose level and a common messenger.
#include <TG4Verbose.h>
Public Member Functions
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Private Member Functions
TG4Verbose ()
Not implemented.
TG4Verbose (const TG4Verbose &right)
Not implemented.
TG4Verbose & operator= (const TG4Verbose &right)
Not implemented.
TG4VerboseMessenger * CreateMessenger ()
Private Attributes
G4int fVerboseLevel
verbose level
G4UIcommand * fCommand
verbose command
Static Private Attributes
static const G4int fgkDefaultVerboseLevel = 1
default verbose level
static const G4String fgkDirectoryName = "/mcVerbose/"
directory name
static G4ThreadLocal G4int fgCounter = 0
object counter
static G4ThreadLocal TG4VerboseMessenger * fgMessenger = 0
messenger
Detailed Description
Base class for defining the verbose level and a common messenger.
Class defines the verbose level and the static messenger (common for all instances). Used as a base class for all Geant4 VMC verbose classes; enables to handle the standard output in a common way.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 35 of file TG4Verbose.h.
Constructor & Destructor Documentation
TG4Verbose() [1/4]
TG4Verbose::TG4Verbose (const G4String & cmdName)
Standard constructor with specified name
Definition at line 24 of file TG4Verbose.cxx.
Referenced by operator=(), TG4ComposedPhysicsList::TG4ComposedPhysicsList(), TG4CrossSectionManager::TG4CrossSectionManager(), TG4EmPhysicsList::TG4EmPhysicsList(), TG4EventAction::TG4EventAction(), TG4ExtDecayer::TG4ExtDecayer(), TG4ExtraPhysicsList::TG4ExtraPhysicsList(), TG4GeometryManager::TG4GeometryManager(), TG4GeometryServices::TG4GeometryServices(), TG4GeoTrackManager::TG4GeoTrackManager(), TG4HadronPhysicsList::TG4HadronPhysicsList(), TG4MCGeometry::TG4MCGeometry(), TG4ModelConfigurationManager::TG4ModelConfigurationManager(), TG4OpGeometryManager::TG4OpGeometryManager(), TG4ParticlesChecker::TG4ParticlesChecker(), TG4ParticlesManager::TG4ParticlesManager(), TG4PhysicsManager::TG4PhysicsManager(), TG4PrimaryGeneratorAction::TG4PrimaryGeneratorAction(), TG4RunAction::TG4RunAction(), TG4RunManager::TG4RunManager(), TG4SDConstruction::TG4SDConstruction(), TG4SpecialControlsV2::TG4SpecialControlsV2(), TG4SpecialPhysicsList::TG4SpecialPhysicsList(), TG4SpecialPhysicsList::TG4SpecialPhysicsList(), TG4SpecialStackingAction::TG4SpecialStackingAction(), TG4StateManager::TG4StateManager(), TG4TrackingAction::TG4TrackingAction(), TG4TrackManager::TG4TrackManager(), TG4Verbose(), TG4VPhysicsConstructor::TG4VPhysicsConstructor(), TG4VPhysicsConstructor::TG4VPhysicsConstructor(), TG4VRegionsManager::TG4VRegionsManager(), TG4ComposedPhysicsList::VerboseLevel(), TG4EmPhysicsList::VerboseLevel(), TG4ExtraPhysicsList::VerboseLevel(), and TG4SpecialPhysicsList::VerboseLevel().
TG4Verbose() [2/4]
TG4Verbose::TG4Verbose (const G4String & cmdName, G4int verboseLevel)
Standard constructor with specified name and verboseLevel
Definition at line 37 of file TG4Verbose.cxx.
~TG4Verbose()
TG4Verbose::~TG4Verbose () virtual
Destructor
Definition at line 50 of file TG4Verbose.cxx.
TG4Verbose() [3/4]
TG4Verbose::TG4Verbose () private
Not implemented.
TG4Verbose() [4/4]
TG4Verbose::TG4Verbose (const TG4Verbose & right) private
Not implemented.
Member Function Documentation
VerboseLevel() [1/2]
void TG4Verbose::VerboseLevel (G4int level) inline virtual
Set level of verbosity
Reimplemented in TG4ComposedPhysicsList, TG4EmPhysicsList, TG4ExtraPhysicsList, TG4HadronPhysicsList, TG4SpecialPhysicsList, and TG4VPhysicsConstructor.
Definition at line 72 of file TG4Verbose.h.
Referenced by TG4ActionInitialization::Build(), TG4ExtDecayerPhysics::ConstructProcess(), TG4PhysicsManager::SetProcessActivation(), TG4ComposedPhysicsList::TG4ComposedPhysicsList(), TG4EmPhysicsList::TG4EmPhysicsList(), TG4ExtraPhysicsList::TG4ExtraPhysicsList(), TG4HadronPhysicsList::TG4HadronPhysicsList(), TG4SpecialPhysicsList::TG4SpecialPhysicsList(), TG4SpecialPhysicsList::TG4SpecialPhysicsList(), TG4TrackManager::TrackToStack(), TG4ComposedPhysicsList::VerboseLevel(), TG4EmPhysicsList::VerboseLevel(), TG4ExtraPhysicsList::VerboseLevel(), and TG4SpecialPhysicsList::VerboseLevel().
VerboseLevel() [2/2]
G4int TG4Verbose::VerboseLevel () const inline virtual
Return level of verbosity
Reimplemented in TG4ComposedPhysicsList, TG4EmPhysicsList, TG4ExtraPhysicsList, TG4HadronPhysicsList, TG4SpecialPhysicsList, and TG4VPhysicsConstructor.
Definition at line 78 of file TG4Verbose.h.
Referenced by TG4ParticlesManager::AddIon(), TG4ParticlesManager::AddParticle(), TG4ParticlesManager::AddParticleToPdgDatabase(), TG4PrimaryGeneratorAction::AddParticleToVertex(), TG4SDConstruction::AddSelection(), TG4SpecialControlsV2::ApplyControls(), TG4EventAction::BeginOfEventAction(), TG4RunAction::BeginOfRunAction(), TG4RunAction::ChangeLooperParameters(), TG4ParticlesChecker::CheckName(), TG4ParticlesChecker::CheckParticles(), TG4ParticlesChecker::CheckProperty(), TG4VRegionsManager::CheckRegionsInGeometry(), TG4RegionsManager::CheckRegionsRanges(), TG4RunManager::CloneRootNavigatorForWorker(), TG4SpecialPhysicsList::Configure(), TG4RunManager::ConfigureRunManager(), TG4SDConstruction::Construct(), TG4GeometryManager::ConstructG4Geometry(), TG4GeometryManager::ConstructG4GeometryViaVGM(), TG4GeometryManager::ConstructG4GeometryViaVMC(), TG4GeometryManager::ConstructGlobalField(), TG4GeometryManager::ConstructLocalFields(), TG4GeometryManager::ConstructSDandField(), TG4GeometryManager::ConstructZeroFields(), TG4RegionsManager::ConvertEnergyToRange(), TG4BiasingManager::CreateBiasingOperator(), TG4GeometryManager::CreateField(), TG4ModelConfigurationManager::CreateRegions(), TG4SDConstruction::CreateSD(), TG4ParticlesManager::DefineParticles(), TG4RegionsManager2::DefineRegions(), TG4RegionsManager::DefineRegions(), TG4EventAction::EndOfEventAction(), TG4RunAction::EndOfRunAction(), TG4CrossSectionManager::FillHistograms(), TG4GeometryManager::FillMediumMapFromG3(), TG4GeometryManager::FillMediumMapFromG4(), TG4GeometryManager::FillMediumMapFromRoot(), TG4GeometryManager::FinishGeometry(), TG4RegionsManager::GetRangeCut(), TG4PhysicsManager::Gstpar(), TG4PhysicsManager::GstparControl(), TG4PhysicsManager::GstparCut(), TG4ExtDecayer::ImportDecayProducts(), TG4RunManager::Initialize(), TG4RegionsManager::Iterate(), TG4RunManager::LateInitialize(), TG4RegionsManager::LoadRegions(), TG4SDConstruction::MapVolumesToInstanceIds(), TG4SDConstruction::MapVolumesToSDIds(), TG4GeometryServices::MixMaterials(), TG4SpecialStackingAction::NewStage(), TG4GeometryManager::PrintFieldStatistics(), TG4VRegionsManager::SaveRegions(), TG4OpGeometryManager::SetCerenkov(), TG4ParticlesManager::SetDecayMode(), TG4GeometryManager::SetIsLocalField(), TG4GeometryManager::SetIsMaxStepInLowDensityMaterials(), TG4GeometryManager::SetIsMonopoleField(), TG4GeometryManager::SetIsUserMaxStep(), TG4GeometryManager::SetIsZeroField(), TG4OpGeometryManager::SetMaterialProperty(), TG4OpGeometryManager::SetMaterialProperty(), TG4OpGeometryManager::SetMaterialProperty(), TG4ModelConfigurationManager::SetModel(), TG4StateManager::SetNewState(), TG4ModelConfigurationManager::SetRegionsNames(), TG4SpecialControlsV2::SetSwitch(), TG4TrackManager::SetTrackInformation(), TG4GeometryManager::SetUserLimits(), TG4BiasingManager::TG4BiasingManager(), TG4ModelConfigurationManager::TG4ModelConfigurationManager(), TG4RunAction::TG4RunAction(), TG4RunManager::TG4RunManager(), TG4PrimaryGeneratorAction::TransformPrimaries(), TG4PrimaryGeneratorAction::TransformTracks(), TG4RegionsManager2::UpdateProductionCutsTable(), TG4GeoTrackManager::UpdateRootTrack(), TG4TrackingAction::Verbose(), TG4ComposedPhysicsList::VerboseLevel(), TG4ComposedPhysicsList::VerboseLevel(), TG4EmPhysicsList::VerboseLevel(), TG4EmPhysicsList::VerboseLevel(), TG4ExtraPhysicsList::VerboseLevel(), TG4ExtraPhysicsList::VerboseLevel(), TG4HadronPhysicsList::VerboseLevel(), TG4HadronPhysicsList::VerboseLevel(), TG4SpecialPhysicsList::VerboseLevel(), TG4SpecialPhysicsList::VerboseLevel(), TG4VPhysicsConstructor::VerboseLevel(), TG4VPhysicsConstructor::VerboseLevel(), and TG4RunAction::~TG4RunAction().
operator=()
TG4Verbose & TG4Verbose::operator= (const TG4Verbose & right) private
Not implemented.
CreateMessenger()
TG4VerboseMessenger * TG4Verbose::CreateMessenger () private
Create static messenger if it does not yet exists.
Definition at line 74 of file TG4Verbose.cxx.
Referenced by TG4Verbose(), and TG4Verbose().
Member Data Documentation
fgkDefaultVerboseLevel
const G4int TG4Verbose::fgkDefaultVerboseLevel = 1 static private
default verbose level
Definition at line 60 of file TG4Verbose.h.
Referenced by TG4Verbose().
fgkDirectoryName
const G4String TG4Verbose::fgkDirectoryName = "/mcVerbose/" static private
directory name
Definition at line 61 of file TG4Verbose.h.
Referenced by CreateMessenger().
fgCounter
G4ThreadLocal G4int TG4Verbose::fgCounter = 0 static private
object counter
Definition at line 62 of file TG4Verbose.h.
Referenced by TG4Verbose(), TG4Verbose(), and ~TG4Verbose().
fgMessenger
G4ThreadLocal TG4VerboseMessenger * TG4Verbose::fgMessenger = 0 static private
messenger
Definition at line 63 of file TG4Verbose.h.
Referenced by CreateMessenger(), TG4Verbose(), TG4Verbose(), and ~TG4Verbose().
fVerboseLevel
G4int TG4Verbose::fVerboseLevel private
verbose level
Definition at line 66 of file TG4Verbose.h.
Referenced by TG4Verbose(), TG4Verbose(), VerboseLevel(), and VerboseLevel().
fCommand
G4UIcommand* TG4Verbose::fCommand private
verbose command
Definition at line 67 of file TG4Verbose.h.
Referenced by TG4Verbose(), TG4Verbose(), and ~TG4Verbose().
The documentation for this class was generated from the following files:
source/global/include/TG4Verbose.h
source/global/src/TG4Verbose.cxx