Geant4 VMC: G4Monopole Class Reference
G4Monopole Class Reference
physics_monopole
#include <Doxymodules.h>
Public Member Functions
G4double MagneticCharge () const
Static Public Member Functions
static G4Monopole * MonopoleDefinition (G4double mass=100.*CLHEP::GeV, G4double magCharge=1.0, G4double elCharge=0.0)
static G4Monopole * Monopole ()
Private Member Functions
G4Monopole (const G4String &aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String &pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable *decaytable)
virtual ~G4Monopole ()
Static Private Attributes
static G4Monopole * theMonopole = 0
static G4double magCharge = 0.0
Detailed Description
Definition at line 48 of file Doxymodules.h.
Constructor & Destructor Documentation
G4Monopole()
G4Monopole::G4Monopole (const G4String & aName, G4double mass, G4double width, G4double charge, G4int iSpin, G4int iParity, G4int iConjugation, G4int iIsospin, G4int iIsospin3, G4int gParity, const G4String & pType, G4int lepton, G4int baryon, G4int encoding, G4bool stable, G4double lifetime, G4DecayTable * decaytable) private
Definition at line 63 of file G4Monopole.cxx.
Referenced by Monopole(), and MonopoleDefinition().
~G4Monopole()
G4Monopole::~G4Monopole () private virtual
Definition at line 75 of file G4Monopole.cxx.
Member Function Documentation
MonopoleDefinition()
G4Monopole * G4Monopole::MonopoleDefinition (G4double mass = 100.*CLHEP::GeV, G4double magCharge = 1.0, G4double elCharge = 0.0) static
Definition at line 88 of file G4Monopole.cxx.
Referenced by G4MonopolePhysics::ConstructParticle(), and Monopole().
Monopole()
G4Monopole * G4Monopole::Monopole () static
Definition at line 105 of file G4Monopole.cxx.
MagneticCharge()
G4double G4Monopole::MagneticCharge () const
Definition at line 115 of file G4Monopole.cxx.
Referenced by TG4ParticlesManager::DefineParticles().
Member Data Documentation
theMonopole
G4Monopole * G4Monopole::theMonopole = 0 static private
Definition at line 65 of file G4Monopole.hh.
Referenced by Monopole(), MonopoleDefinition(), and ~G4Monopole().
magCharge
G4double G4Monopole::magCharge = 0.0 static private
Definition at line 92 of file G4Monopole.hh.
Referenced by MagneticCharge(), and MonopoleDefinition().
The documentation for this class was generated from the following files:
source/Doxymodules.h
source/physics_monopole/include/G4Monopole.hh
source/physics_monopole/src/G4Monopole.cxx