Geant4 VMC: TG4ProcessMapPhysics Class Reference
TG4ProcessMapPhysics Class Reference
physics_list
The special builder which fills the VMC process map.
#include <TG4ProcessMapPhysics.h>
Public Member Functions
TG4ProcessMapPhysics (const G4String &name="ProcessMap")
TG4ProcessMapPhysics (G4int theVerboseLevel, const G4String &name="ProcessMap")
TG4ProcessMapPhysics (const TG4ProcessMapPhysics &right)=delete
TG4ProcessMapPhysics & operator= (const TG4ProcessMapPhysics &right)=delete
~TG4ProcessMapPhysics () override
Public Member Functions inherited from TG4VPhysicsConstructor
TG4VPhysicsConstructor (const G4String &name)
TG4VPhysicsConstructor (const G4String &name, G4int theVerboseLevel)
virtual ~TG4VPhysicsConstructor ()
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
Protected Member Functions
void ConstructParticle () override
Construct particles.
void ConstructProcess () override
Construct physics processes.
Protected Member Functions inherited from TG4VPhysicsConstructor
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Private Member Functions
void FillMap ()
void UpdateHadronicProcessSubType (G4VProcess *process)
G4bool UpdateOrSkipBiasingProcess (G4VProcess *process)
Detailed Description
The special builder which fills the VMC process map.
Author
I. Hrivnacova; IJCLab, Orsay
Definition at line 49 of file TG4ProcessMapPhysics.h.
Constructor & Destructor Documentation
TG4ProcessMapPhysics() [1/3]
TG4ProcessMapPhysics::TG4ProcessMapPhysics (const G4String & name = "ProcessMap")
Standard constructor
Definition at line 40 of file TG4ProcessMapPhysics.cxx.
Referenced by operator=(), and TG4ProcessMapPhysics().
TG4ProcessMapPhysics() [2/3]
TG4ProcessMapPhysics::TG4ProcessMapPhysics (G4int theVerboseLevel, const G4String & name = "ProcessMap")
Standard constructor
Definition at line 49 of file TG4ProcessMapPhysics.cxx.
TG4ProcessMapPhysics() [3/3]
TG4ProcessMapPhysics::TG4ProcessMapPhysics (const TG4ProcessMapPhysics & right) delete
~TG4ProcessMapPhysics()
TG4ProcessMapPhysics::~TG4ProcessMapPhysics () override
Destructor
Definition at line 59 of file TG4ProcessMapPhysics.cxx.
Member Function Documentation
operator=()
TG4ProcessMapPhysics & TG4ProcessMapPhysics::operator= (const TG4ProcessMapPhysics & right) delete
ConstructParticle()
void TG4ProcessMapPhysics::ConstructParticle () override protected virtual
Construct particles.
Instantiate particles - nothing to be done here
Implements TG4VPhysicsConstructor.
Definition at line 240 of file TG4ProcessMapPhysics.cxx.
ConstructProcess()
void TG4ProcessMapPhysics::ConstructProcess () override protected virtual
Construct physics processes.
Loop over all particles and their processes and check if the process is present in the map
Implements TG4VPhysicsConstructor.
Definition at line 246 of file TG4ProcessMapPhysics.cxx.
FillMap()
void TG4ProcessMapPhysics::FillMap () private
Fill the process codes map with known G4 process names
Definition at line 69 of file TG4ProcessMapPhysics.cxx.
Referenced by TG4ProcessMapPhysics(), and TG4ProcessMapPhysics().
UpdateHadronicProcessSubType()
void TG4ProcessMapPhysics::UpdateHadronicProcessSubType (G4VProcess * process) private
Update process sub type codes for hadronic processes which are not set in Geant4 itself
Definition at line 187 of file TG4ProcessMapPhysics.cxx.
Referenced by ConstructProcess().
UpdateOrSkipBiasingProcess()
G4bool TG4ProcessMapPhysics::UpdateOrSkipBiasingProcess (G4VProcess * process) private
Skip a biasing wrapper process, if it has not defined sub type
Definition at line 213 of file TG4ProcessMapPhysics.cxx.
Referenced by ConstructProcess().
The documentation for this class was generated from the following files:
source/physics_list/include/TG4ProcessMapPhysics.h
source/physics_list/src/TG4ProcessMapPhysics.cxx