Geant4 VMC: TG4G3ControlVector Class Reference
TG4G3ControlVector Class Reference
global
Vector of control process values with convenient set/get methods.
#include <TG4G3ControlVector.h>
Public Types
typedef std::vector< TG4G3ControlValue > TG4ControlValueVector
The vector of TG4G3ControlValue.
Public Member Functions
TG4G3ControlVector ()
TG4G3ControlVector (const TG4G3ControlVector &right)
~TG4G3ControlVector ()
TG4G3ControlVector & operator= (const TG4G3ControlVector &right)
TG4G3ControlValue operator[] (G4int index) const
G4bool SetControl (TG4G3Control control, TG4G3ControlValue controlValue, TG4G3CutVector &cuts)
void SetG3Defaults ()
G4bool Update (const TG4G3ControlVector &vector)
G4String Format () const
void Print () const
TG4G3ControlValue GetControlValue (G4VProcess *process) const
TG4G3ControlValue GetControlValue (TG4G3Control control) const
G4bool IsControl () const
Static Public Member Functions
static TG4G3Control GetControl (const G4String &controlName)
static const G4String & GetControlName (TG4G3Control control)
static TG4G3ControlValue GetControlValue (G4int value, TG4G3Control control)
static TG4G3ControlValue GetControlValue (G4double value, TG4G3Control control)
Static Private Member Functions
static void FillControlNameVector ()
Private Attributes
TG4ControlValueVector fControlVector
vector of control process values
Static Private Attributes
static TG4StringVector fgControlNameVector
vector of control parameters names
Detailed Description
Vector of control process values with convenient set/get methods.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 32 of file TG4G3ControlVector.h.
Member Typedef Documentation
TG4ControlValueVector
typedef std::vector<TG4G3ControlValue> TG4G3ControlVector::TG4ControlValueVector
The vector of TG4G3ControlValue.
Definition at line 36 of file TG4G3ControlVector.h.
Constructor & Destructor Documentation
TG4G3ControlVector() [1/2]
TG4G3ControlVector::TG4G3ControlVector ()
Default constructor
Definition at line 34 of file TG4G3ControlVector.cxx.
Referenced by operator=(), TG4G3ControlVector(), and Update().
TG4G3ControlVector() [2/2]
TG4G3ControlVector::TG4G3ControlVector (const TG4G3ControlVector & right)
Copy constructor
Definition at line 47 of file TG4G3ControlVector.cxx.
~TG4G3ControlVector()
TG4G3ControlVector::~TG4G3ControlVector ()
Destructor
Definition at line 57 of file TG4G3ControlVector.cxx.
Member Function Documentation
operator=()
TG4G3ControlVector & TG4G3ControlVector::operator= (const TG4G3ControlVector & right)
Assignment operator
Definition at line 67 of file TG4G3ControlVector.cxx.
operator[]()
TG4G3ControlValue TG4G3ControlVector::operator[] (G4int index) const
Element access operator
Definition at line 83 of file TG4G3ControlVector.cxx.
GetControl()
TG4G3Control TG4G3ControlVector::GetControl (const G4String & controlName) static
Retrieve corresponding TG4G3Control constant from the controlName.
Definition at line 129 of file TG4G3ControlVector.cxx.
Referenced by TG4G3PhysicsManager::CheckControlWithTheVector(), TG4GeometryServices::PrintControls(), and TG4PhysicsManager::SetProcess().
GetControlName()
const G4String & TG4G3ControlVector::GetControlName (TG4G3Control control) static
Return name of a specified cut.
Definition at line 170 of file TG4G3ControlVector.cxx.
Referenced by TG4ProcessMap::GetControlName(), and TG4ProcessMap::PrintAll().
GetControlValue() [1/4]
TG4G3ControlValue TG4G3ControlVector::GetControlValue (G4int value, TG4G3Control control) static
Conversion G4int -> G3ControlValue, special treatment for LOSS values 3,4,5.
Definition at line 182 of file TG4G3ControlVector.cxx.
Referenced by TG4G3PhysicsManager::CheckControlWithTheVector(), GetControlValue(), SetControl(), TG4PhysicsManager::SetProcess(), and TG4PhysicsManager::SetSpecialControlsActivation().
GetControlValue() [2/4]
TG4G3ControlValue TG4G3ControlVector::GetControlValue (G4double value, TG4G3Control control) static
Conversion G4double -> G3ControlValue
Definition at line 215 of file TG4G3ControlVector.cxx.
SetControl()
G4bool TG4G3ControlVector::SetControl (TG4G3Control control, TG4G3ControlValue controlValue, TG4G3CutVector & cuts)
Set the controlValue for the specified process control. Modify cuts if necessary. Return true if the control value was set.
Definition at line 224 of file TG4G3ControlVector.cxx.
Referenced by SetControl().
SetG3Defaults()
void TG4G3ControlVector::SetG3Defaults ()
Set G3 default values for all controls.
Definition at line 251 of file TG4G3ControlVector.cxx.
Update()
G4bool TG4G3ControlVector::Update (const TG4G3ControlVector & vector)
Unset value of DRAY (this information was passed to cut vector.) Reset value of LOSS (the special controls process operates only with activate/inactivate options.) Return true if some value was modified.
Definition at line 260 of file TG4G3ControlVector.cxx.
Format()
G4String TG4G3ControlVector::Format () const
Format the output into a string.
Definition at line 297 of file TG4G3ControlVector.cxx.
Referenced by Print().
Print()
void TG4G3ControlVector::Print () const
Print the controls.
Definition at line 318 of file TG4G3ControlVector.cxx.
Referenced by TG4ComposedPhysicsMessenger::SetNewValue().
GetControlValue() [3/4]
TG4G3ControlValue TG4G3ControlVector::GetControlValue (G4VProcess * process) const
Return the control value for the particle associated with the specified process.
Definition at line 326 of file TG4G3ControlVector.cxx.
GetControlValue() [4/4]
TG4G3ControlValue TG4G3ControlVector::GetControlValue (TG4G3Control control) const
Return the control value for the particle associated with the specified process.
Definition at line 337 of file TG4G3ControlVector.cxx.
IsControl()
G4bool TG4G3ControlVector::IsControl () const
Return true if any of controls is set.
Definition at line 347 of file TG4G3ControlVector.cxx.
FillControlNameVector()
void TG4G3ControlVector::FillControlNameVector () static private
Define fControlNameVector.
Definition at line 101 of file TG4G3ControlVector.cxx.
Referenced by GetControlName(), and TG4G3ControlVector().
Member Data Documentation
fgControlNameVector
TG4StringVector TG4G3ControlVector::fgControlNameVector static private
vector of control parameters names
Definition at line 77 of file TG4G3ControlVector.h.
Referenced by FillControlNameVector(), Format(), GetControl(), GetControlName(), and TG4G3ControlVector().
fControlVector
TG4ControlValueVector TG4G3ControlVector::fControlVector private
vector of control process values
Definition at line 83 of file TG4G3ControlVector.h.
Referenced by Format(), GetControlValue(), GetControlValue(), IsControl(), operator=(), operator[](), SetControl(), SetG3Defaults(), TG4G3ControlVector(), TG4G3ControlVector(), and Update().
The documentation for this class was generated from the following files:
source/global/include/TG4G3ControlVector.h
source/global/src/TG4G3ControlVector.cxx