Geant4 VMC: TG4VSpecialCuts Class Reference
TG4VSpecialCuts Class Reference abstract
physics
Abstract base class for a special process that activates kinetic energy cuts.
#include <TG4VSpecialCuts.h>
Public Member Functions
TG4VSpecialCuts (const G4String &processName)
virtual ~TG4VSpecialCuts ()
virtual G4double GetMinEkine (const TG4Limits &limits, const G4Track &track) const =0
Return the kinetic energy limit.
virtual G4double PostStepGetPhysicalInteractionLength (const G4Track &track, G4double previousStepSize, G4ForceCondition *condition)
virtual G4VParticleChange * PostStepDoIt (const G4Track &track, const G4Step &step)
virtual G4double AlongStepGetPhysicalInteractionLength (const G4Track &, G4double, G4double, G4double &, G4GPILSelection *)
Not implemented.
virtual G4VParticleChange * AlongStepDoIt (const G4Track &, const G4Step &)
Not implemented.
virtual G4double AtRestGetPhysicalInteractionLength (const G4Track &, G4ForceCondition *)
Not implemented.
virtual G4VParticleChange * AtRestDoIt (const G4Track &, const G4Step &)
Not implemented.
Private Member Functions
TG4VSpecialCuts ()
Not implemented.
TG4VSpecialCuts (const TG4VSpecialCuts &right)
Not implemented.
TG4VSpecialCuts & operator= (const TG4VSpecialCuts &right)
Not implemented.
Private Attributes
G4LossTableManager * fLossTableManager
The G4LossTableManager instance.
TG4TrackManager * fTrackManager
Cached pointer to thread-local track manager.
Detailed Description
Abstract base class for a special process that activates kinetic energy cuts.
The pure virtual functions GetMinEkine have to be implemented by derived classes specific for each particle type (see TG4G3ParticleWSP.h).
Author
I. Hrivnacova; IPN Orsay
Definition at line 37 of file TG4VSpecialCuts.h.
Constructor & Destructor Documentation
TG4VSpecialCuts() [1/3]
TG4VSpecialCuts::TG4VSpecialCuts (const G4String & processName)
Standard constructor
Definition at line 29 of file TG4VSpecialCuts.cxx.
Referenced by operator=(), TG4SpecialCutsForChargedHadron::TG4SpecialCutsForChargedHadron(), TG4SpecialCutsForElectron::TG4SpecialCutsForElectron(), TG4SpecialCutsForGamma::TG4SpecialCutsForGamma(), TG4SpecialCutsForMuon::TG4SpecialCutsForMuon(), TG4SpecialCutsForNeutralHadron::TG4SpecialCutsForNeutralHadron(), TG4SpecialCutsForNeutron::TG4SpecialCutsForNeutron(), and TG4VSpecialCuts().
~TG4VSpecialCuts()
TG4VSpecialCuts::~TG4VSpecialCuts () virtual
Destructor
Definition at line 40 of file TG4VSpecialCuts.cxx.
TG4VSpecialCuts() [2/3]
TG4VSpecialCuts::TG4VSpecialCuts () private
Not implemented.
TG4VSpecialCuts() [3/3]
TG4VSpecialCuts::TG4VSpecialCuts (const TG4VSpecialCuts & right) private
Not implemented.
Member Function Documentation
GetMinEkine()
virtual G4double TG4VSpecialCuts::GetMinEkine (const TG4Limits & limits, const G4Track & track) const pure virtual
Return the kinetic energy limit.
Implemented in TG4SpecialCutsForChargedHadron, TG4SpecialCutsForElectron, TG4SpecialCutsForGamma, TG4SpecialCutsForMuon, TG4SpecialCutsForNeutralHadron, and TG4SpecialCutsForNeutron.
Referenced by PostStepGetPhysicalInteractionLength().
PostStepGetPhysicalInteractionLength()
G4double TG4VSpecialCuts::PostStepGetPhysicalInteractionLength (const G4Track & track, G4double previousStepSize, G4ForceCondition * condition) virtual
Return the Step-size (actual length) which is allowed by this process.
Definition at line 50 of file TG4VSpecialCuts.cxx.
PostStepDoIt()
G4VParticleChange * TG4VSpecialCuts::PostStepDoIt (const G4Track & track, const G4Step & step) virtual
Kill the current particle, if requested by G4UserLimits. Set its status fStopButAlive (instead of previously used fStopAndKill to let execute the at rest processes (decay)
Reimplemented in TG4SpecialCutsForNeutron.
Definition at line 125 of file TG4VSpecialCuts.cxx.
AlongStepGetPhysicalInteractionLength()
virtual G4double TG4VSpecialCuts::AlongStepGetPhysicalInteractionLength (const G4Track & , G4double , G4double , G4double & , G4GPILSelection *) inline virtual
Not implemented.
Definition at line 55 of file TG4VSpecialCuts.h.
AlongStepDoIt()
virtual G4VParticleChange * TG4VSpecialCuts::AlongStepDoIt (const G4Track & , const G4Step &) inline virtual
Not implemented.
Definition at line 62 of file TG4VSpecialCuts.h.
AtRestGetPhysicalInteractionLength()
virtual G4double TG4VSpecialCuts::AtRestGetPhysicalInteractionLength (const G4Track & , G4ForceCondition *) inline virtual
Not implemented.
Definition at line 68 of file TG4VSpecialCuts.h.
AtRestDoIt()
virtual G4VParticleChange * TG4VSpecialCuts::AtRestDoIt (const G4Track & , const G4Step &) inline virtual
Not implemented.
Definition at line 75 of file TG4VSpecialCuts.h.
operator=()
TG4VSpecialCuts & TG4VSpecialCuts::operator= (const TG4VSpecialCuts & right) private
Not implemented.
Member Data Documentation
fLossTableManager
G4LossTableManager* TG4VSpecialCuts::fLossTableManager private
The G4LossTableManager instance.
Definition at line 89 of file TG4VSpecialCuts.h.
Referenced by PostStepGetPhysicalInteractionLength(), and TG4VSpecialCuts().
fTrackManager
TG4TrackManager* TG4VSpecialCuts::fTrackManager private
Cached pointer to thread-local track manager.
Definition at line 92 of file TG4VSpecialCuts.h.
Referenced by PostStepGetPhysicalInteractionLength(), and TG4VSpecialCuts().
The documentation for this class was generated from the following files:
source/physics/include/TG4VSpecialCuts.h
source/physics/src/TG4VSpecialCuts.cxx