Geant4 VMC: TG4G3Units Class Reference
TG4G3Units Class Reference
global
G3 default units of physical quantities;.
#include <TG4G3Units.h>
Public Member Functions
~TG4G3Units ()
Static Public Member Functions
static G4double Length ()
static G4double Angle ()
static G4double Time ()
static G4double Charge ()
static G4double Energy ()
static G4double Mass ()
static G4double MassDensity ()
static G4double AtomicWeight ()
static G4double Field ()
static G4double InverseLength ()
static G4double InverseAngle ()
static G4double InverseTime ()
static G4double InverseCharge ()
static G4double InverseEnergy ()
static G4double InverseMass ()
static G4double InverseMassDensity ()
static G4double InverseAtomicWeight ()
static G4double InverseField ()
Private Member Functions
TG4G3Units ()
Static Private Attributes
static const G4double fgkLength = cm
G3 length unit.
static const G4double fgkAngle = deg
G3 angle unit.
static const G4double fgkTime = s
G3 time unit.
static const G4double fgkCharge = eplus
G3 charge unit.
static const G4double fgkEnergy = GeV
G3 energy unit.
static const G4double fgkMass = GeV
G3 mass unit.
static const G4double fgkMassDensity = g / cm3
G3 mass density unit.
static const G4double fgkAtomicWeight = g / mole
G3 atomic weight unit.
static const G4double fgkField = kilogauss
G3 magnetic field unit.
static const G4double fgkInverseLength = 1. / cm
1 over G3 length unit
static const G4double fgkInverseAngle = 1. / deg
1 over G3 angle unit
static const G4double fgkInverseTime = 1. / s
1 over G3 time unit
static const G4double fgkInverseCharge = 1. / eplus
1 over G3 charge unit
static const G4double fgkInverseEnergy = 1. / GeV
1 over G3 energy unit
static const G4double fgkInverseMass = 1. / GeV
1 over G3 mass unit
static const G4double fgkInverseMassDensity = 1. / g * cm3
1 over G3 mass density unit
static const G4double fgkInverseAtomicWeight = 1. / g * mole
1 over G3 atomic weight unit
static const G4double fgkInverseField = 1. / kilogauss
1 over G3 magnetic field unit
Detailed Description
G3 default units of physical quantities;.
All physical quantities returned by VMC are expressed in these units.
Author
I. Hrivnacova; IPN, Orsay
Definition at line 27 of file TG4G3Units.h.
Constructor & Destructor Documentation
~TG4G3Units()
TG4G3Units::~TG4G3Units ()
Destructor
Definition at line 42 of file TG4G3Units.cxx.
TG4G3Units()
TG4G3Units::TG4G3Units () private
Member Function Documentation
Length()
G4double TG4G3Units::Length () inline static
Return G3 length unit
Definition at line 81 of file TG4G3Units.h.
Referenced by TG4OpGeometryManager::AddUnit(), TG4StepManager::CurrentMaterial(), TG4StepManager::Gdtom(), TG4MCGeometry::GetMaterial(), TG4OpGeometryManager::GetMaterial(), TG4ParticlesManager::GetParticlePosition(), TG4StepManager::GetSecondary(), TG4OpGeometryManager::Gfmate(), TG4StepManager::Gmtod(), TG4StepManager::MaxStep(), TG4TrackManager::PrimaryToStack(), TG4SteppingAction::ProcessTrackIfOutOfRegion(), TG4OpGeometryManager::SetCerenkov(), TG4StepManager::SetMaxStep(), TG4DetConstructionMessenger::SetNewValue(), TG4StepManager::TrackPosition(), TG4StepManager::TrackPosition(), TG4TrackManager::TrackToStack(), and TG4PrimaryGeneratorAction::TransformTracks().
Angle()
G4double TG4G3Units::Angle () inline static
Return G3 angle unit
Definition at line 87 of file TG4G3Units.h.
Time()
G4double TG4G3Units::Time () inline static
Return G3 time unit
Definition at line 93 of file TG4G3Units.h.
Referenced by TG4ParticlesManager::AddParticle(), TG4OpGeometryManager::AddUnit(), TG4G3PhysicsManager::CheckCutWithTheVector(), TG4StepManager::ForceDecayTime(), TG4StepManager::GetSecondary(), TG4PhysicsManager::GstparCut(), TG4StackPopper::PostStepDoIt(), TG4PhysicsManager::SetCut(), TG4StepManager::TrackPosition(), TG4PrimaryGeneratorAction::TransformPrimaries(), and TG4PrimaryGeneratorAction::TransformTracks().
Charge()
G4double TG4G3Units::Charge () inline static
Return G3 chanrge unit
Definition at line 99 of file TG4G3Units.h.
Referenced by TG4ParticlesManager::AddParticle(), and TG4StepManager::TrackCharge().
Energy()
G4double TG4G3Units::Energy () inline static
Return G3 energy unit
Definition at line 105 of file TG4G3Units.h.
Referenced by TG4ParticlesManager::AddParticle(), TG4G3PhysicsManager::CheckCutWithTheVector(), TG4PhysicsManager::DefineIon(), TG4ParticlesManager::GetParticleMomentum(), TG4StepManager::GetSecondary(), TG4PhysicsManager::GstparCut(), TG4RegionsManager::LoadRegions(), TG4TrackManager::PrimaryToStack(), TG4OpGeometryManager::SetCerenkov(), TG4PhysicsManager::SetCut(), TG4OpGeometryManager::SetMaterialProperty(), TG4OpGeometryManager::SetMaterialProperty(), TG4StepManager::TrackMomentum(), TG4StepManager::TrackMomentum(), TG4TrackManager::TrackToStack(), TG4PrimaryGeneratorAction::TransformPrimaries(), and TG4PrimaryGeneratorAction::TransformTracks().
Mass()
G4double TG4G3Units::Mass () inline static
Return G3 mass unit
Definition at line 111 of file TG4G3Units.h.
Referenced by TG4StepManager::TrackMass().
MassDensity()
G4double TG4G3Units::MassDensity () inline static
Return G3 mass density unit
Definition at line 117 of file TG4G3Units.h.
Referenced by TG4StepManager::CurrentMaterial(), TG4MCGeometry::GetMaterial(), TG4OpGeometryManager::GetMaterial(), and TG4OpGeometryManager::Gfmate().
AtomicWeight()
G4double TG4G3Units::AtomicWeight () inline static
Return G3 atomic weight unit
Definition at line 123 of file TG4G3Units.h.
Referenced by TG4GeometryServices::GetEffA().
Field()
G4double TG4G3Units::Field () inline static
Return G3 magnetic field unit
Definition at line 129 of file TG4G3Units.h.
Referenced by TG4MagneticField::GetFieldValue().
InverseLength()
G4double TG4G3Units::InverseLength () inline static
Definition at line 135 of file TG4G3Units.h.
Referenced by TG4StepManager::Gdtom(), TG4MagneticField::GetFieldValue(), TG4StepManager::Gmtod(), TG4StepManager::TrackLength(), and TG4StepManager::TrackStep().
InverseAngle()
G4double TG4G3Units::InverseAngle () inline static
Return G3 angle unit
Definition at line 139 of file TG4G3Units.h.
InverseTime()
G4double TG4G3Units::InverseTime () inline static
Return G3 time unit
Definition at line 145 of file TG4G3Units.h.
Referenced by TG4TrackManager::PrimaryToStack(), TG4StepManager::TrackTime(), and TG4TrackManager::TrackToStack().
InverseCharge()
G4double TG4G3Units::InverseCharge () inline static
Return G3 chanrge unit
Definition at line 151 of file TG4G3Units.h.
Referenced by TG4PhysicsManager::ParticleCharge().
InverseEnergy()
G4double TG4G3Units::InverseEnergy () inline static
Return G3 energy unit
Definition at line 157 of file TG4G3Units.h.
Referenced by TG4ParticlesManager::AddParticleToPdgDatabase(), TG4OpGeometryManager::AddUnit(), TG4StepManager::Edep(), TG4StepManager::Etot(), TG4ExtDecayer::ImportDecayProducts(), TG4StepManager::NIELEdep(), TG4PhysicsManager::ParticleMass(), TG4VRegionsManager::PrintRegionData(), and TG4TrackManager::TrackToStack().
InverseMass()
G4double TG4G3Units::InverseMass () inline static
Return G3 mass unit
Definition at line 163 of file TG4G3Units.h.
InverseMassDensity()
G4double TG4G3Units::InverseMassDensity () inline static
Return G3 mass density unit
Definition at line 169 of file TG4G3Units.h.
Referenced by TG4GeometryServices::CompareMaterial().
InverseAtomicWeight()
G4double TG4G3Units::InverseAtomicWeight () inline static
Return G3 atomic weight unit
Definition at line 175 of file TG4G3Units.h.
InverseField()
G4double TG4G3Units::InverseField () inline static
Return G3 magnetic field unit
Definition at line 181 of file TG4G3Units.h.
Member Data Documentation
fgkLength
const G4double TG4G3Units::fgkLength = cm static private
G3 length unit.
Definition at line 58 of file TG4G3Units.h.
Referenced by Length().
fgkAngle
const G4double TG4G3Units::fgkAngle = deg static private
G3 angle unit.
Definition at line 59 of file TG4G3Units.h.
Referenced by Angle().
fgkTime
const G4double TG4G3Units::fgkTime = s static private
G3 time unit.
Definition at line 60 of file TG4G3Units.h.
Referenced by Time().
fgkCharge
const G4double TG4G3Units::fgkCharge = eplus static private
G3 charge unit.
Definition at line 61 of file TG4G3Units.h.
Referenced by Charge().
fgkEnergy
const G4double TG4G3Units::fgkEnergy = GeV static private
G3 energy unit.
Definition at line 62 of file TG4G3Units.h.
Referenced by Energy().
fgkMass
const G4double TG4G3Units::fgkMass = GeV static private
G3 mass unit.
Definition at line 63 of file TG4G3Units.h.
Referenced by Mass().
fgkMassDensity
const G4double TG4G3Units::fgkMassDensity = g / cm3 static private
G3 mass density unit.
Definition at line 64 of file TG4G3Units.h.
Referenced by MassDensity().
fgkAtomicWeight
const G4double TG4G3Units::fgkAtomicWeight = g / mole static private
G3 atomic weight unit.
Definition at line 65 of file TG4G3Units.h.
Referenced by AtomicWeight().
fgkField
const G4double TG4G3Units::fgkField = kilogauss static private
G3 magnetic field unit.
Definition at line 66 of file TG4G3Units.h.
Referenced by Field().
fgkInverseLength
const G4double TG4G3Units::fgkInverseLength = 1. / cm static private
1 over G3 length unit
Definition at line 68 of file TG4G3Units.h.
Referenced by InverseLength().
fgkInverseAngle
const G4double TG4G3Units::fgkInverseAngle = 1. / deg static private
1 over G3 angle unit
Definition at line 69 of file TG4G3Units.h.
Referenced by InverseAngle().
fgkInverseTime
const G4double TG4G3Units::fgkInverseTime = 1. / s static private
1 over G3 time unit
Definition at line 70 of file TG4G3Units.h.
Referenced by InverseTime().
fgkInverseCharge
const G4double TG4G3Units::fgkInverseCharge = 1. / eplus static private
1 over G3 charge unit
Definition at line 71 of file TG4G3Units.h.
Referenced by InverseCharge().
fgkInverseEnergy
const G4double TG4G3Units::fgkInverseEnergy = 1. / GeV static private
1 over G3 energy unit
Definition at line 72 of file TG4G3Units.h.
Referenced by InverseEnergy().
fgkInverseMass
const G4double TG4G3Units::fgkInverseMass = 1. / GeV static private
1 over G3 mass unit
Definition at line 73 of file TG4G3Units.h.
Referenced by InverseMass().
fgkInverseMassDensity
const G4double TG4G3Units::fgkInverseMassDensity = 1. / g * cm3 static private
1 over G3 mass density unit
Definition at line 74 of file TG4G3Units.h.
Referenced by InverseMassDensity().
fgkInverseAtomicWeight
const G4double TG4G3Units::fgkInverseAtomicWeight = 1. / g * mole static private
1 over G3 atomic weight unit
Definition at line 75 of file TG4G3Units.h.
Referenced by InverseAtomicWeight().
fgkInverseField
const G4double TG4G3Units::fgkInverseField = 1. / kilogauss static private
1 over G3 magnetic field unit
Definition at line 76 of file TG4G3Units.h.
Referenced by InverseField().
The documentation for this class was generated from the following files:
source/global/include/TG4G3Units.h
source/global/src/TG4G3Units.cxx