Geant4 VMC: TG4TrackInformation Class Reference
TG4TrackInformation Class Reference
physics
Defines additional track information.
#include <TG4TrackInformation.h>
Public Member Functions
TG4TrackInformation ()
TG4TrackInformation (G4int trackParticleID)
virtual ~TG4TrackInformation ()
void * operator new (size_t)
Override new operator for G4Allocator.
void operator delete (void *trackInformation)
Override delete operator for G4Allocator.
virtual void Print () const
void SetTrackParticleID (G4int trackParticleID)
void SetParentParticleID (G4int parentParticleID)
void SetPDGLifetime (G4double pdgLifetime)
void SetPDGEncoding (G4int pdgEncoding)
void SetInitialTrackStatus (TMCParticleStatus *status)
void SetIsUserTrack (G4bool isUserTrack)
void SetStop (G4bool stop)
void SetInterrupt (G4bool interrupt)
G4int GetTrackParticleID () const
G4int GetParentParticleID () const
G4double GetPDGLifetime () const
G4int GetPDGEncoding () const
const TMCParticleStatus * GetInitialTrackStatus () const
G4bool IsUserTrack () const
G4bool IsStop () const
G4bool IsInterrupt () const
Private Attributes
G4int fTrackParticleID
the index of track particle in VMC stack
G4int fParentParticleID
the index of parent track in VMC stack
G4double fPDGLifetime
the original particle PDG lifetime
G4double fPDGEncoding
the particle PDG encoding
G4bool fIsUserTrack
true if defined by user and not primary track
G4bool fStop
true if track should be stopped
G4bool fInterrupt
TMCParticleStatus * fInitialTrackStatus
Detailed Description
Defines additional track information.
Author
I. Hrivnacova; IPN Orsay
Definition at line 30 of file TG4TrackInformation.h.
Constructor & Destructor Documentation
TG4TrackInformation() [1/2]
TG4TrackInformation::TG4TrackInformation ()
Default constructor
Definition at line 21 of file TG4TrackInformation.cxx.
TG4TrackInformation() [2/2]
TG4TrackInformation::TG4TrackInformation (G4int trackParticleID)
Standard constructor
Definition at line 36 of file TG4TrackInformation.cxx.
~TG4TrackInformation()
TG4TrackInformation::~TG4TrackInformation () virtual
Destructor
Definition at line 61 of file TG4TrackInformation.cxx.
Member Function Documentation
operator new()
void * TG4TrackInformation::operator new (size_t) inline
Override new operator for G4Allocator.
operator delete()
void TG4TrackInformation::operator delete (void * trackInformation) inline
Override delete operator for G4Allocator.
Print()
void TG4TrackInformation::Print () const virtual
Print track information.
Definition at line 71 of file TG4TrackInformation.cxx.
SetTrackParticleID()
void TG4TrackInformation::SetTrackParticleID (G4int trackParticleID)
Referenced by TG4TrackManager::SetTrackInformation().
SetParentParticleID()
void TG4TrackInformation::SetParentParticleID (G4int parentParticleID)
Referenced by TG4TrackManager::SetParentToTrackInformation(), and TG4TrackManager::SetTrackInformation().
SetPDGLifetime()
void TG4TrackInformation::SetPDGLifetime (G4double pdgLifetime)
Referenced by TG4StepManager::ForceDecayTime().
SetPDGEncoding()
void TG4TrackInformation::SetPDGEncoding (G4int pdgEncoding)
Referenced by TG4StackPopper::PostStepDoIt().
SetInitialTrackStatus()
void TG4TrackInformation::SetInitialTrackStatus (TMCParticleStatus * status)
Referenced by TG4TrackManager::SetTrackInformation().
SetIsUserTrack()
void TG4TrackInformation::SetIsUserTrack (G4bool isUserTrack)
Referenced by TG4StackPopper::PostStepDoIt().
SetStop()
void TG4TrackInformation::SetStop (G4bool stop)
SetInterrupt()
void TG4TrackInformation::SetInterrupt (G4bool interrupt)
GetTrackParticleID()
G4int TG4TrackInformation::GetTrackParticleID () const
Referenced by TG4TrackingAction::PreUserTrackingAction(), TG4TrackManager::SetParentToTrackInformation(), and TG4TrackManager::SetTrackInformation().
GetParentParticleID()
G4int TG4TrackInformation::GetParentParticleID () const
GetPDGLifetime()
G4double TG4TrackInformation::GetPDGLifetime () const
Referenced by TG4TrackManager::SetBackPDGLifetime().
GetPDGEncoding()
G4int TG4TrackInformation::GetPDGEncoding () const
Referenced by TG4StepManager::TrackPid().
GetInitialTrackStatus()
const TMCParticleStatus * TG4TrackInformation::GetInitialTrackStatus () const
Referenced by TG4TrackingAction::PreUserTrackingAction().
IsUserTrack()
G4bool TG4TrackInformation::IsUserTrack () const
Referenced by TG4TrackManager::IsUserTrack().
IsStop()
G4bool TG4TrackInformation::IsStop () const
Referenced by TG4VSpecialCuts::PostStepGetPhysicalInteractionLength().
IsInterrupt()
G4bool TG4TrackInformation::IsInterrupt () const
Member Data Documentation
fTrackParticleID
G4int TG4TrackInformation::fTrackParticleID private
the index of track particle in VMC stack
Definition at line 71 of file TG4TrackInformation.h.
Referenced by Print(), TG4TrackInformation(), and TG4TrackInformation().
fParentParticleID
G4int TG4TrackInformation::fParentParticleID private
the index of parent track in VMC stack
Definition at line 72 of file TG4TrackInformation.h.
Referenced by Print(), TG4TrackInformation(), and TG4TrackInformation().
fPDGLifetime
G4double TG4TrackInformation::fPDGLifetime private
the original particle PDG lifetime
Definition at line 73 of file TG4TrackInformation.h.
Referenced by TG4TrackInformation(), and TG4TrackInformation().
fPDGEncoding
G4double TG4TrackInformation::fPDGEncoding private
the particle PDG encoding
Definition at line 74 of file TG4TrackInformation.h.
Referenced by TG4TrackInformation(), and TG4TrackInformation().
fIsUserTrack
G4bool TG4TrackInformation::fIsUserTrack private
true if defined by user and not primary track
Definition at line 75 of file TG4TrackInformation.h.
Referenced by Print(), TG4TrackInformation(), and TG4TrackInformation().
fStop
G4bool TG4TrackInformation::fStop private
true if track should be stopped
Definition at line 76 of file TG4TrackInformation.h.
Referenced by Print(), TG4TrackInformation(), and TG4TrackInformation().
fInterrupt
G4bool TG4TrackInformation::fInterrupt private
true if track should be interrupted
Definition at line 77 of file TG4TrackInformation.h.
Referenced by TG4TrackInformation(), and TG4TrackInformation().
fInitialTrackStatus
TMCParticleStatus* TG4TrackInformation::fInitialTrackStatus private
Pointer holds some additional information on the particle status e.g. for the case the track has already been transported up to the current point in another engine.
Definition at line 81 of file TG4TrackInformation.h.
Referenced by Print(), TG4TrackInformation(), and TG4TrackInformation().
The documentation for this class was generated from the following files:
source/physics/include/TG4TrackInformation.h
source/physics/src/TG4TrackInformation.cxx