Geant4 VMC: TG4ExtraPhysicsList Class Reference
TG4ExtraPhysicsList Class Reference
physics_list
The physics list with extra physics builders.
#include <TG4ExtraPhysicsList.h>
Public Member Functions
TG4ExtraPhysicsList (const G4String &selection, const std::map< TString, Double_t > &parameters)
virtual ~TG4ExtraPhysicsList ()
virtual void ConstructProcess ()
virtual void SetCuts ()
No cuts are set here.
virtual G4int VerboseLevel () const
virtual void VerboseLevel (G4int level)
void SetRangeCut (G4double value)
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
Static Public Member Functions
static G4String AvailableSelections ()
static G4bool IsAvailableSelection (const G4String &selection)
Static Protected Attributes
static const G4double fgkDefaultCutValue = 1.0 * mm
default cut value
Private Member Functions
TG4ExtraPhysicsList (const TG4ExtraPhysicsList &right)
Not implemented.
TG4ExtraPhysicsList & operator= (const TG4ExtraPhysicsList &right)
Not implemented.
void Configure (const G4String &, const std::map< TString, Double_t > &parameters)
Detailed Description
The physics list with extra physics builders.
The physics list is implemented as modular physics list with the following physics builders: G4EmExtraPhysics, G4OpticalPhysics and G4RadioactiveDecayPhysics
The builders are activated according to the user selection. The EM extra physics processes are not activated by default. If extra builder is selected, they can be then switched on using the following Geant4 commands:
/physics_engine/tailor/SyncRadiation on
/physics_engine/tailor/GammaNuclear on
/physics_engine/tailor/MuonNuclear on
Author
I. Hrivnacova; IPN Orsay
Definition at line 46 of file TG4ExtraPhysicsList.h.
Constructor & Destructor Documentation
TG4ExtraPhysicsList() [1/2]
TG4ExtraPhysicsList::TG4ExtraPhysicsList (const G4String & selection, const std::map< TString, Double_t > & parameters)
Default constructor
Definition at line 104 of file TG4ExtraPhysicsList.cxx.
Referenced by operator=(), and TG4ExtraPhysicsList().
~TG4ExtraPhysicsList()
TG4ExtraPhysicsList::~TG4ExtraPhysicsList () virtual
Destructor
Definition at line 118 of file TG4ExtraPhysicsList.cxx.
TG4ExtraPhysicsList() [2/2]
TG4ExtraPhysicsList::TG4ExtraPhysicsList (const TG4ExtraPhysicsList & right) private
Not implemented.
Member Function Documentation
AvailableSelections()
G4String TG4ExtraPhysicsList::AvailableSelections () static
Return list of all available selections
Definition at line 77 of file TG4ExtraPhysicsList.cxx.
Referenced by IsAvailableSelection(), and TG4RunConfiguration::TG4RunConfiguration().
IsAvailableSelection()
G4bool TG4ExtraPhysicsList::IsAvailableSelection (const G4String & selection) static
Return list of all available selections
Definition at line 88 of file TG4ExtraPhysicsList.cxx.
Referenced by TG4RunConfiguration::CreatePhysicsList(), and TG4RunConfiguration::TG4RunConfiguration().
ConstructProcess()
void TG4ExtraPhysicsList::ConstructProcess () virtual
Call base class method + add verbose info
Definition at line 191 of file TG4ExtraPhysicsList.cxx.
SetCuts()
virtual void TG4ExtraPhysicsList::SetCuts () inline virtual
No cuts are set here.
Definition at line 61 of file TG4ExtraPhysicsList.h.
VerboseLevel() [1/2]
G4int TG4ExtraPhysicsList::VerboseLevel () const virtual
Return verbose level (via TG4Verbose)
Reimplemented from TG4Verbose.
Definition at line 215 of file TG4ExtraPhysicsList.cxx.
Referenced by ConstructProcess().
VerboseLevel() [2/2]
void TG4ExtraPhysicsList::VerboseLevel (G4int level) virtual
Set the specified level to both TG4Verbose and G4VModularPhysicsList. The verbose level is also propagated to registered physics contructors.
Reimplemented from TG4Verbose.
Definition at line 223 of file TG4ExtraPhysicsList.cxx.
SetRangeCut()
void TG4ExtraPhysicsList::SetRangeCut (G4double value)
Reset the default cut to a given value.
!!! Should be used only in PreInit phase, use SetDefaultCutValue() method of base class to reset the cut value in later phases.
Definition at line 244 of file TG4ExtraPhysicsList.cxx.
operator=()
TG4ExtraPhysicsList & TG4ExtraPhysicsList::operator= (const TG4ExtraPhysicsList & right) private
Not implemented.
Configure()
void TG4ExtraPhysicsList::Configure (const G4String & selection, const std::map< TString, Double_t > & parameters) private
Create the selected physics constructors and registeres them in the modular physics list.
Definition at line 128 of file TG4ExtraPhysicsList.cxx.
Referenced by TG4ExtraPhysicsList().
Member Data Documentation
fgkDefaultCutValue
const G4double TG4ExtraPhysicsList::fgkDefaultCutValue = 1.0 * mm static protected
default cut value
Definition at line 71 of file TG4ExtraPhysicsList.h.
Referenced by TG4ExtraPhysicsList().
The documentation for this class was generated from the following files:
source/physics_list/include/TG4ExtraPhysicsList.h
source/physics_list/src/TG4ExtraPhysicsList.cxx