Geant4 VMC: TG4ModelConfigurationManager Class Reference
TG4ModelConfigurationManager Class Reference
physics_list
The model configuration vector with suitable setters and a messenger.
#include <TG4ModelConfigurationManager.h>
Public Types
typedef std::vector< TG4ModelConfiguration * > ModelConfigurationVector
Public Member Functions
TG4ModelConfigurationManager (const G4String &name, const G4String &availableModels="")
virtual ~TG4ModelConfigurationManager ()
void CreateRegions ()
void SetModel (const G4String &modelName)
void SetModelParticles (const G4String &modelName, const G4String &particles)
void SetModelExcludedParticles (const G4String &modelName, const G4String &particles)
void SetModelRegions (const G4String &modelName, const G4String &regionsMedia)
void SetOneModelRegion (const G4String &modelName, const G4String &regionMedium)
G4String GetName () const
G4String GetAvailableModels () const
TG4ModelConfiguration * GetModelConfiguration (const G4String &modelName, G4bool warn=true) const
const ModelConfigurationVector & GetVector () const
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
virtual void VerboseLevel (G4int level)
virtual G4int VerboseLevel () const
Protected Member Functions
void SetRegionsNames ()
Private Member Functions
TG4ModelConfigurationManager (const TG4ModelConfigurationManager &right)
Not implemented.
TG4ModelConfigurationManager & operator= (const TG4ModelConfigurationManager &right)
Not implemented.
Private Attributes
TG4ModelConfigurationMessenger * fMessenger
Messenger.
G4String fName
The associated physics builder name.
G4String fAvailableModels
List of available models.
ModelConfigurationVector fVector
Vector of registered model configurations.
G4bool fCreateRegionsDone
Info whether regions were constructed.
Detailed Description
The model configuration vector with suitable setters and a messenger.
Author
I. Hrivnacova; IPN Orsay
Definition at line 32 of file TG4ModelConfigurationManager.h.
Member Typedef Documentation
ModelConfigurationVector
typedef std::vector<TG4ModelConfiguration*> TG4ModelConfigurationManager::ModelConfigurationVector
Definition at line 35 of file TG4ModelConfigurationManager.h.
Constructor & Destructor Documentation
TG4ModelConfigurationManager() [1/2]
TG4ModelConfigurationManager::TG4ModelConfigurationManager (const G4String & name, const G4String & availableModels = "")
Standard constructor
Definition at line 43 of file TG4ModelConfigurationManager.cxx.
Referenced by operator=(), TG4BiasingManager::TG4BiasingManager(), and TG4ModelConfigurationManager().
~TG4ModelConfigurationManager()
TG4ModelConfigurationManager::~TG4ModelConfigurationManager () virtual
Destructor
Definition at line 64 of file TG4ModelConfigurationManager.cxx.
TG4ModelConfigurationManager() [2/2]
TG4ModelConfigurationManager::TG4ModelConfigurationManager (const TG4ModelConfigurationManager & right) private
Not implemented.
Member Function Documentation
CreateRegions()
void TG4ModelConfigurationManager::CreateRegions ()
Create regions for all registered models
Definition at line 152 of file TG4ModelConfigurationManager.cxx.
SetModel()
void TG4ModelConfigurationManager::SetModel (const G4String & modelName)
Set an extra EM model with the given name.
Definition at line 227 of file TG4ModelConfigurationManager.cxx.
SetModelParticles()
void TG4ModelConfigurationManager::SetModelParticles (const G4String & modelName, const G4String & particles)
Set particles for the physics model for given medium.
Definition at line 247 of file TG4ModelConfigurationManager.cxx.
SetModelExcludedParticles()
void TG4ModelConfigurationManager::SetModelExcludedParticles (const G4String & modelName, const G4String & particles)
Set particles for the physics model for given medium.
Definition at line 268 of file TG4ModelConfigurationManager.cxx.
SetModelRegions()
void TG4ModelConfigurationManager::SetModelRegions (const G4String & modelName, const G4String & regionsMedia)
Set regions for the physics model for given media.
Definition at line 289 of file TG4ModelConfigurationManager.cxx.
SetOneModelRegion()
void TG4ModelConfigurationManager::SetOneModelRegion (const G4String & modelName, const G4String & regionMedium)
Set regions for the physics model for the given medium.
Definition at line 310 of file TG4ModelConfigurationManager.cxx.
GetName()
G4String TG4ModelConfigurationManager::GetName () const inline
Return the associated physics builder name
Definition at line 91 of file TG4ModelConfigurationManager.h.
GetAvailableModels()
G4String TG4ModelConfigurationManager::GetAvailableModels () const inline
Return the list of available models
Definition at line 97 of file TG4ModelConfigurationManager.h.
GetModelConfiguration()
TG4ModelConfiguration * TG4ModelConfigurationManager::GetModelConfiguration (const G4String & modelName, G4bool warn = true) const
Return the model configuration via specified model name; print warning if a configuration is not found
Definition at line 330 of file TG4ModelConfigurationManager.cxx.
Referenced by SetModel(), SetModelExcludedParticles(), SetModelParticles(), SetModelRegions(), and SetOneModelRegion().
GetVector()
const TG4ModelConfigurationManager::ModelConfigurationVector & TG4ModelConfigurationManager::GetVector () const inline
Return the vector of registered model configurations
Definition at line 104 of file TG4ModelConfigurationManager.h.
Referenced by TG4EmModelPhysics::ConstructProcess(), TG4FastSimulationPhysics::ConstructProcess(), and TG4BiasingManager::CreateBiasingOperator().
SetRegionsNames()
void TG4ModelConfigurationManager::SetRegionsNames () protected
Set the regions names (corresponding to material names) to model configurations. This conversion is needed to be consistent with regions defined with special cuts, which are defined per materiials.
Definition at line 81 of file TG4ModelConfigurationManager.cxx.
Referenced by TG4BiasingManager::CreateBiasingOperator(), and CreateRegions().
operator=()
TG4ModelConfigurationManager & TG4ModelConfigurationManager::operator= (const TG4ModelConfigurationManager & right) private
Not implemented.
Member Data Documentation
fMessenger
TG4ModelConfigurationMessenger* TG4ModelConfigurationManager::fMessenger private
Messenger.
messenger
Definition at line 74 of file TG4ModelConfigurationManager.h.
Referenced by TG4ModelConfigurationManager(), and ~TG4ModelConfigurationManager().
fName
G4String TG4ModelConfigurationManager::fName private
The associated physics builder name.
Definition at line 77 of file TG4ModelConfigurationManager.h.
Referenced by GetName(), and TG4ModelConfigurationManager().
fAvailableModels
G4String TG4ModelConfigurationManager::fAvailableModels private
List of available models.
Definition at line 80 of file TG4ModelConfigurationManager.h.
Referenced by GetAvailableModels(), and TG4ModelConfigurationManager().
fVector
ModelConfigurationVector TG4ModelConfigurationManager::fVector private
Vector of registered model configurations.
Definition at line 83 of file TG4ModelConfigurationManager.h.
Referenced by CreateRegions(), GetModelConfiguration(), GetVector(), SetModel(), SetRegionsNames(), TG4ModelConfigurationManager(), and ~TG4ModelConfigurationManager().
fCreateRegionsDone
G4bool TG4ModelConfigurationManager::fCreateRegionsDone private
Info whether regions were constructed.
Definition at line 86 of file TG4ModelConfigurationManager.h.
Referenced by CreateRegions(), and TG4ModelConfigurationManager().
The documentation for this class was generated from the following files:
source/global/include/TG4ModelConfigurationManager.h
source/global/src/TG4ModelConfigurationManager.cxx