Geant4 VMC: TG4EmPhysicsList Class Reference
TG4EmPhysicsList Class Reference
physics_list
The standard EM physics list.
#include <TG4EmPhysicsList.h>
Public Member Functions
TG4EmPhysicsList (const G4String &selection="emStandard")
virtual ~TG4EmPhysicsList ()
virtual void ConstructProcess ()
virtual void SetCuts ()
No cuts are set here.
virtual G4int VerboseLevel () const
virtual void VerboseLevel (G4int level)
void SetRangeCut (G4double value)
Public Member Functions inherited from TG4Verbose
TG4Verbose (const G4String &cmdName)
TG4Verbose (const G4String &cmdName, G4int verboseLevel)
virtual ~TG4Verbose ()
Static Public Member Functions
static G4String AvailableSelections ()
static G4bool IsAvailableSelection (const G4String &selection)
Static Protected Attributes
static const G4double fgkDefaultCutValue = 1.0 * mm
default cut value
Private Member Functions
TG4EmPhysicsList (const TG4EmPhysicsList &right)
Not implemented.
TG4EmPhysicsList & operator= (const TG4EmPhysicsList &right)
Not implemented.
void Configure (const G4String &)
Detailed Description
The standard EM physics list.
The EM physics list is implemented as modular physics list with registered G4EmStandardPhysics and G4DecayPhysics builders,
Author
I. Hrivnacova; IPN Orsay
Definition at line 32 of file TG4EmPhysicsList.h.
Constructor & Destructor Documentation
TG4EmPhysicsList() [1/2]
TG4EmPhysicsList::TG4EmPhysicsList (const G4String & selection = "emStandard")
Default constructor
Definition at line 66 of file TG4EmPhysicsList.cxx.
Referenced by operator=(), and TG4EmPhysicsList().
~TG4EmPhysicsList()
TG4EmPhysicsList::~TG4EmPhysicsList () virtual
Destructor
Definition at line 79 of file TG4EmPhysicsList.cxx.
TG4EmPhysicsList() [2/2]
TG4EmPhysicsList::TG4EmPhysicsList (const TG4EmPhysicsList & right) private
Not implemented.
Member Function Documentation
AvailableSelections()
G4String TG4EmPhysicsList::AvailableSelections () static
Return list of all available selections
Definition at line 39 of file TG4EmPhysicsList.cxx.
Referenced by IsAvailableSelection(), and TG4RunConfiguration::TG4RunConfiguration().
IsAvailableSelection()
G4bool TG4EmPhysicsList::IsAvailableSelection (const G4String & selection) static
Return list of all available selections
Definition at line 50 of file TG4EmPhysicsList.cxx.
Referenced by TG4RunConfiguration::CreatePhysicsList(), and TG4RunConfiguration::TG4RunConfiguration().
ConstructProcess()
void TG4EmPhysicsList::ConstructProcess () virtual
Call ase class method + add verbose info
Definition at line 109 of file TG4EmPhysicsList.cxx.
SetCuts()
virtual void TG4EmPhysicsList::SetCuts () inline virtual
No cuts are set here.
Definition at line 46 of file TG4EmPhysicsList.h.
VerboseLevel() [1/2]
G4int TG4EmPhysicsList::VerboseLevel () const virtual
Return verbose level (via TG4Verbose)
Reimplemented from TG4Verbose.
Definition at line 120 of file TG4EmPhysicsList.cxx.
Referenced by ConstructProcess().
VerboseLevel() [2/2]
void TG4EmPhysicsList::VerboseLevel (G4int level) virtual
Set the specified level to both TG4Verbose and G4VModularPhysicsList. The verbose level is also propagated to registered physics contructors.
Reimplemented from TG4Verbose.
Definition at line 128 of file TG4EmPhysicsList.cxx.
SetRangeCut()
void TG4EmPhysicsList::SetRangeCut (G4double value)
Reset the default cut to a given value.
!!! Should be used only in PreInit phase, use SetDefaultCutValue() method of base class to reset the cut value in later phases.
Definition at line 149 of file TG4EmPhysicsList.cxx.
operator=()
TG4EmPhysicsList & TG4EmPhysicsList::operator= (const TG4EmPhysicsList & right) private
Not implemented.
Configure()
void TG4EmPhysicsList::Configure (const G4String &) private
Create the selected physics constructors and registeres them in the modular physics list.
Definition at line 92 of file TG4EmPhysicsList.cxx.
Referenced by TG4EmPhysicsList().
Member Data Documentation
fgkDefaultCutValue
const G4double TG4EmPhysicsList::fgkDefaultCutValue = 1.0 * mm static protected
default cut value
Definition at line 56 of file TG4EmPhysicsList.h.
Referenced by TG4EmPhysicsList().
The documentation for this class was generated from the following files:
source/physics_list/include/TG4EmPhysicsList.h
source/physics_list/src/TG4EmPhysicsList.cxx