Geant4 VMC: source/physics/src/TG4CrossSectionType.cxx File Reference
TG4CrossSectionType.cxx File Reference
Definition of the enumeration TG4CrossSectionType.
#include "TG4CrossSectionType.h"
Functions
G4String TG4CrossSectionTypeName (G4int type)
Return name for given cross section type.
TG4CrossSectionType GetCrossSectionType (G4int type)
Convert G4int to TG4CrossSectionType (for loops)
TG4CrossSectionType GetCrossSectionType (G4String name)
Return the cross section type by name.
Detailed Description
Definition of the enumeration TG4CrossSectionType.
Author
I. Hrivnacova; IPN, Orsay
Definition in file TG4CrossSectionType.cxx.
Function Documentation
TG4CrossSectionTypeName()
G4String TG4CrossSectionTypeName (G4int type)
Return name for given cross section type.
Definition at line 18 of file TG4CrossSectionType.cxx.
Referenced by GetCrossSectionType(), TG4CrossSectionManager::PrintCrossSection(), TG4CrossSectionManager::PrintCrossSections(), and TG4CrossSectionMessenger::TG4CrossSectionMessenger().
GetCrossSectionType() [1/2]
TG4CrossSectionType GetCrossSectionType (G4int type)
Convert G4int to TG4CrossSectionType (for loops)
Definition at line 37 of file TG4CrossSectionType.cxx.
Referenced by TG4CrossSectionManager::PrintCrossSections(), and TG4CrossSectionMessenger::SetNewValue().
GetCrossSectionType() [2/2]
TG4CrossSectionType GetCrossSectionType (G4String name)
Return the cross section type by name.
Definition at line 56 of file TG4CrossSectionType.cxx.